### ISSUE TITLE
Panic when filename has ":" in Windows

### ISSUE THREAD

**Issue by ironsand** [gohugoio/hugo#10026]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66 windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

yes

### How to reproduce the bug

```
hugo new "Foo:.md"
panic: [BUG] no Page found for "C:\\Users\\ironsand\\www\\mysite\\content\\Foo:.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc000278b40, {0xc0000399c0, 0x37}, {0xc0006d53c0, 0xa})
        /root/project/hugo/create/content.go:276 +0x354
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc000278b40)
        /root/project/hugo/create/content.go:244 +0x1ad
github.com/gohugoio/hugo/create.NewContent.func1()
        /root/project/hugo/create/content.go:104 +0x2ad
github.com/gohugoio/hugo/create.NewContent(0xc000180f20, {0x0, 0x0}, {0xc00011e080, 0x5a80a5})
        /root/project/hugo/create/content.go:108 +0x5fe
github.com/gohugoio/hugo/commands.(*newCmd).newContent(0xc0006b5e60, 0xc000424f00, {0xc0002dccd0, 0x1, 0x0})
        /root/project/hugo/commands/new.go:83 +0x150
github.com/spf13/cobra.(*Command).execute(0xc000424f00, {0xc0002dcca0, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00089b900)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/gohugoio/hugo/commands.Execute({0xc00014a010, 0x2, 0x3})
        /root/project/hugo/commands/hugo.go:92 +0xb4
main.main()
        /root/project/hugo/main.go:23 +0x58
exit status 2
```

When the filename has "*", the command returns proper error message.
```
hugo new "Foo*.md"

Error: CreateFile C:\Users\ironsand\www\mysite\content\Foo*.md: The filename, directory name, or volume label syntax is incorrect.
exit status 4294967295
```

**Comment by stackkrocket** [comment]
@ironsand I suppose the "*" label after the file name means it is an executable file which perhaps has been set as an incorrect label in the hugo source code which throws the appropriate error message.  

And I reckon any other label such as ":" does not make much sense to compiler hence the type of error message you are getting.  Although I may be completely off the mark here.

**Comment by f0restOfHimalayas** [comment]
Hi 
I would like to contribute to this issue if that's okay. I have done some initial analysis for this.
