### ISSUE TITLE
sever sometimes crashes when you modify a page

### ISSUE THREAD

**Issue by hsn10** [gohugoio/hugo#10047]
Server mode has been _always_ problematic, it crashes when you modify a file. In this case I modified a plain content page. I haven't seen this one yet. It doesn't always crash (maybe 1:50), so my guess is lack of locking somewhere.

<pre>
hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64
</pre>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x2624921]

goroutine 147 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc0002842d0, 0xc0010bce40, 0xc000ba0178, {0xc002814000?, 0x16, 0x20}, 0xf56abd?)
        /root/project/hugo/commands/hugo.go:1114 +0x721
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
        /root/project/hugo/commands/hugo.go:895 +0x26c
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /root/project/hugo/commands/hugo.go:886 +0x3ca
```

**Comment by jmooring** [comment]
This is fixed in v0.123.0.
