### ISSUE TITLE
Arch Linux RE: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by zayn7lie** [gohugoio/hugo#11135]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.112.3+extended linux/amd64 BuildDate=unknown
</pre>

### Does this issue reproduce with the latest release?
```sh
$ hugo
Total in 9 ms
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/gohugoio/hugo/modules.ApplyProjectConfigDefaults({0x564c66dc56a0?, 0xc000003200}, {0x564c67ef0d48, 0x0, 0x1?})
        github.com/gohugoio/hugo/modules/config.go:89 +0x109d
github.com/gohugoio/hugo/config/allconfig.(*Configs).Init(0xc000867000)
        github.com/gohugoio/hugo/config/allconfig/allconfig.go:648 +0x206
github.com/gohugoio/hugo/config/allconfig.LoadConfig({{0x564c66dc4ee0, 0x564c67ef06e0}, {0x564c66dc7c70, 0xc0002275c0}, {0x564c66dc5d10, 0xc0001727c0}, {0x0, 0x0}, {0x564c66206d95, 0x6}, ...})
        github.com/gohugoio/hugo/config/allconfig/load.go:88 +0x8f7
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider.func1(0x227658?)
        github.com/gohugoio/hugo/commands/commandeer.go:222 +0x358
github.com/bep/lazycache.(*Cache[...]).GetOrCreate(0x564c66dd2b20, 0x0, 0xc000e619c0?)
        github.com/bep/lazycache@v0.2.0/lazycache.go:112 +0x142
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider(0xc0004b7940?, 0x66dc5d10?, {0x564c66dc5d10, 0xc0001727c0})
        github.com/gohugoio/hugo/commands/commandeer.go:198 +0x68
github.com/gohugoio/hugo/commands.(*hugoBuilder).loadConfig(0xc00026f980, 0x0?, 0x0)
        github.com/gohugoio/hugo/commands/hugobuilder.go:1017 +0x3aa
github.com/gohugoio/hugo/commands.(*rootCommand).Run(0xc0001f0780, {0x0?, 0x0?}, 0x0?, {0x0?, 0x0?, 0x0?})
        github.com/gohugoio/hugo/commands/commandeer.go:342 +0xf1
github.com/bep/simplecobra.(*Commandeer).compile.func1(0xc000005800?, {0x564c67ef0d48?, 0x0?, 0x0?})
        github.com/bep/simplecobra@v0.3.1/simplecobra.go:113 +0x52
github.com/spf13/cobra.(*Command).execute(0xc000005800, {0xc000040240, 0x0, 0x0})
        github.com/spf13/cobra@v1.7.0/command.go:940 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0xc000005800)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
        github.com/spf13/cobra@v1.7.0/command.go:1001
github.com/bep/simplecobra.(*Exec).Execute(0xc0000155a0, {0x564c66dba130?, 0xc0000440e8?}, {0xc000040240?, 0x564c64814be8?, 0xc000089168?})
        github.com/bep/simplecobra@v0.3.1/simplecobra.go:155 +0xd9
github.com/gohugoio/hugo/commands.Execute({0xc000040240, 0x0, 0x0})
        github.com/gohugoio/hugo/commands/commandeer.go:65 +0x312
main.main()
        github.com/gohugoio/hugo/main.go:25 +0x65
```

Similar to #6924

**Comment by bep** [comment]
>Similar to https://github.com/gohugoio/hugo/issues/6924

Well, not really.

You should check your configuration, somehow you end up with 0 languages.
