### ISSUE TITLE
Hugo crashing when configuring permalinks

### ISSUE THREAD

**Issue by schaefsteven** [gohugoio/hugo#11433]
I was trying to configure the structure of my site as per this documentation: https://gohugo.io/content-management/urls/#permalinks

I added this to my config.toml: 
```
[permalinks]
    [permalinks.page]
        links = '/:slug/'
```

And I got this error message: 
```
panic: runtime error: slice bounds out of range [1:0]

goroutine 328 [running]:
github.com/gohugoio/hugo/resources/page.PermalinkExpander.validate({0xc00f323560?, 0x0?, 0xc00f322ff0?}, {0x0?, 0x0?})
	/root/project/hugo/resources/page/permalinks.go:183 +0x21b
github.com/gohugoio/hugo/resources/page.PermalinkExpander.parse({0xc00f323560?, 0x0?, 0xc00f322ff0?}, 0x8?)
	/root/project/hugo/resources/page/permalinks.go:126 +0x136
github.com/gohugoio/hugo/resources/page.NewPermalinkExpander(0xc00f322ff0)
	/root/project/hugo/resources/page/permalinks.go:95 +0x7a5
github.com/gohugoio/hugo/resources.NewSpec(0xc00f322ff0, 0xc00f323020, {0x28ae740, 0xc00f306fa8}, {0x28cda90, 0xc00f322090}, {0x28ae760?, 0xc00dc1ca00}, 0xc00d816dc0, {0xc00f31a600, ...}, ...)
	/root/project/hugo/resources/resource_spec.go:76 +0x1e5
github.com/gohugoio/hugo/deps.New({{0x28cda90, 0xc00f322090}, 0xc00d869dc0, 0xc00dc09700, {0x0, 0x0}, {0x28cac20, 0xc00dc12b00}, {0xc00f327000, 0x23, ...}, ...})
	/root/project/hugo/deps/deps.go:291 +0x6e5
github.com/gohugoio/hugo/hugolib.configLoader.applyDeps({{0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)
	/root/project/hugo/hugolib/hugo_sites.go:518 +0x31e
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x28cda90, 0xc00f322090}, 0xc00d869dc0, 0x0, {0x0, 0x0}, {0x28cac20, 0xc00dc12b00}, {0x0, 0x0, ...}, ...}, ...)
	/root/project/hugo/hugolib/hugo_sites.go:405 +0x766
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x28cda90, 0xc00f322090}, 0xc00d869dc0, 0x0, {0x0, 0x0}, {0x28cac20, 0xc00dc12b00}, {0x0, 0x0, ...}, ...})
	/root/project/hugo/hugolib/hugo_sites.go:554 +0x158
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/root/project/hugo/commands/commandeer.go:501 +0x8d8
sync.(*Once).doSlow(0xc00dc12b00?, 0x225a241?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0009b6a00)
	/root/project/hugo/commands/commandeer.go:426 +0xa9e
github.com/gohugoio/hugo/commands.(*commandeer).fullRebuild.func1()
	/root/project/hugo/commands/hugo.go:810 +0x185
created by github.com/gohugoio/hugo/commands.(*commandeer).fullRebuild
	/root/project/hugo/commands/hugo.go:795 +0x116
ERROR: "hugo:serve" exited with 2.
```

I tried several different variations of the toml and also tried running hugo instead of hugo serve. All similar results. 

Is this because I'm not defining the permalinks for every page and section in my site? I tried defining all of the pages, but no luck. 

What does work however is a format that I don't see in the documentation: 
```
[permalinks]
    links = '/:slug/'
```
The above config does work for what I want to do, but it is not mentioned in the documentation, and attempting to use the format specified in the docs is leading to crashes. 

Gitub link to repo at this commit: https://github.com/schaefsteven/rocky-hutchins/tree/42a52dedafa9fa32a4ce87c7dc77f96d9db56806

**Comment by jmooring** [comment]
Version?

**Comment by schaefsteven** [comment]
I am running hugo with npm. 
```
$ npx hugo version
hugo v0.111.3-5d4eb5154e1fed125ca8e9b5a0315c4180dab192+extended linux/amd64 BuildDate=2023-03-12T11:40:50Z VendorInfo=gohugoio
```

**Comment by jmooring** [comment]
Can you reproduce the problem with the current release? v0.118.2.

**Comment by jmooring** [comment]
The ability to set permalinks by page kind was added in [v0.115.0](https://github.com/gohugoio/hugo/releases/tag/v0.115.0).
