### ISSUE TITLE
hugo server panic: interface conversion: interface {} is []interface {}, not maps.Params

### ISSUE THREAD

**Issue by neitsab** [gohugoio/hugo#11793]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.1-00b46fed8e47f7bb0a85d7cfc2d9f1356379b740+extended linux/amd64 BuildDate=2023-12-08T08:47:45Z VendorInfo=gohugoio
</pre>

(Also happens with Arch-provided `hugo v0.120.1+extended linux/amd64 BuildDate=unknown`)

### Does this issue reproduce with the latest release?

Yes

After trying to use `hugo server` on a site I hadn't touched in over a year I got this panic:

```go
% hugo server
panic: interface conversion: interface {} is []interface {}, not maps.Params

goroutine 1 [running]:
github.com/gohugoio/hugo/config/allconfig.fromLoadConfigResult({0x55c0d52fb618, 0x55c0d6633500}, {0x55c0d5303218, 0xc000708b00}, {{0x55c0d52fd5c8, 0xc0002ccd80}, {0xc000399d30, 0x1, 0x1}, {{0xc000058034, ...}, ...}})
	github.com/gohugoio/hugo/config/allconfig/allconfig.go:771 +0x1a96
github.com/gohugoio/hugo/config/allconfig.LoadConfig({{0x55c0d52fb618, 0x55c0d6633500}, {0x55c0d5303218, 0xc000708b00}, {0x55c0d52fd5c8, 0xc0002ccd40}, {0x0, 0x0}, {0x55c0d370d1b3, 0x6}, ...})
	github.com/gohugoio/hugo/config/allconfig/load.go:62 +0x4e5
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider.func1(0x3aede8?)
	github.com/gohugoio/hugo/commands/commandeer.go:217 +0x338
github.com/bep/lazycache.(*Cache[...]).GetOrCreate(0x55c0d530a460, 0x0, 0xc0009bfa00?)
	github.com/bep/lazycache@v0.2.0/lazycache.go:112 +0x136
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider(0xc0002e9c40?, 0xd52fd5c8?, {0x55c0d52fd5c8, 0xc0002ccd40})
	github.com/gohugoio/hugo/commands/commandeer.go:193 +0x5e
github.com/gohugoio/hugo/commands.(*hugoBuilder).loadConfig(0xc000708b80, 0x6?, 0x1)
	github.com/gohugoio/hugo/commands/hugobuilder.go:997 +0x3b6
github.com/gohugoio/hugo/commands.(*serverCommand).PreRun(0xc000863180, 0xc0002e9c40, 0xc0002e9c40?)
	github.com/gohugoio/hugo/commands/server.go:604 +0x3f2
github.com/bep/simplecobra.(*Commandeer).init(0xc0002e9c40)
	github.com/bep/simplecobra@v0.3.2/simplecobra.go:92 +0xc5
github.com/bep/simplecobra.(*Commandeer).compile.func2(0xc000b19a00?, {0x55c0d3705244?, 0x4?, 0x55c0d3705070?})
	github.com/bep/simplecobra@v0.3.2/simplecobra.go:119 +0x17
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0x55c0d6633500, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:925 +0x7f6
github.com/spf13/cobra.(*Command).ExecuteC(0xc00027f500)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	github.com/spf13/cobra@v1.7.0/command.go:1001
github.com/bep/simplecobra.(*Exec).Execute(0xc00011fb68, {0x55c0d52f0d68?, 0x55c0d6633500?}, {0xc000132010?, 0x1d18d2201?, 0x0?})
	github.com/bep/simplecobra@v0.3.2/simplecobra.go:155 +0xd4
github.com/gohugoio/hugo/commands.Execute({0xc000132010, 0x1, 0x1})
	github.com/gohugoio/hugo/commands/commandeer.go:65 +0x2f9
main.main()
	github.com/gohugoio/hugo/main.go:25 +0x56
```

Here's the repo: https://gitlab.com/neitsab/bastientraverse.com. There is a git submodule pointing to a personally maintained fork of the theme, if that is of any relevance.

Got other panics while running `hugo mod clean` and `hugo mod clean --all` (seen in the forum):

```go
% hugo mod clean
panic: interface conversion: interface {} is []interface {}, not maps.Params

goroutine 1 [running]:
github.com/gohugoio/hugo/config/allconfig.fromLoadConfigResult({0x3ecd420, 0x528a040}, {0x3ed6198, 0xc00098e500}, {{0x3ecf3a8, 0xc000161a40}, {0xc0005a2bd0, 0x1, 0x1}, {{0xc000058034, ...}, ...}})
	/root/project/hugo/config/allconfig/allconfig.go:771 +0x1a96
github.com/gohugoio/hugo/config/allconfig.LoadConfig({{0x3ecd420, 0x528a040}, {0x3ed6198, 0xc00098e500}, {0x3ecf3a8, 0xc000161a00}, {0x0, 0x0}, {0x288be78, 0x6}, ...})
	/root/project/hugo/config/allconfig/load.go:61 +0x4e5
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider.func1(0x3859e8?)
	/root/project/hugo/commands/commandeer.go:217 +0x338
github.com/bep/lazycache.(*Cache[...]).GetOrCreate(0x3ee09c0, 0x219f500, 0xc000a3f820?)
	/root/project/gomodcache/github.com/bep/lazycache@v0.2.0/lazycache.go:112 +0x12a
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider(0x4d8105?, 0x703ea0?, {0x3ecf3a8, 0xc000161a00})
	/root/project/hugo/commands/commandeer.go:193 +0x5e
github.com/gohugoio/hugo/commands.(*rootCommand).Hugo.func1(0x385b38?)
	/root/project/hugo/commands/commandeer.go:315 +0x35
github.com/bep/lazycache.(*Cache[...]).GetOrCreate(0x3ee0840, 0x0, 0xc000a3f9d8?)
	/root/project/gomodcache/github.com/bep/lazycache@v0.2.0/lazycache.go:112 +0x12a
github.com/gohugoio/hugo/commands.(*rootCommand).Hugo(0xc0001612c0?, {0x3ecf3a8?, 0xc000161a00?})
	/root/project/hugo/commands/commandeer.go:314 +0x59
github.com/gohugoio/hugo/commands.newModCommands.func10({0x0?, 0x0?}, 0x0?, 0xc0009997c0, {0x0?, 0x0?, 0x0?})
	/root/project/hugo/commands/mod.go:152 +0x50
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x3ec2298?, 0x528a040?}, 0x0?, {0x528a040?, 0x0?, 0x0?})
	/root/project/hugo/commands/commandeer.go:588 +0x3c
github.com/bep/simplecobra.(*Commandeer).compile.func1(0xc000991200?, {0x528a040?, 0x4?, 0x2883d41?})
	/root/project/gomodcache/github.com/bep/simplecobra@v0.4.0/simplecobra.go:113 +0x4c
github.com/spf13/cobra.(*Command).execute(0xc00044f200, {0x528a040, 0x0, 0x0})
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004c00)
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/bep/simplecobra.(*Exec).Execute(0xc0005a6408, {0x3ec2298?, 0x528a040?}, {0xc000052370?, 0x100506901?, 0x0?})
	/root/project/gomodcache/github.com/bep/simplecobra@v0.4.0/simplecobra.go:155 +0xd4
github.com/gohugoio/hugo/commands.Execute({0xc000052370, 0x2, 0x2})
	/root/project/hugo/commands/commandeer.go:65 +0x2f9
main.main()
	/root/project/hugo/main.go:25 +0x56
```

I tried to do a clean clone but go another panic:

```
git clone --recurse-submodules https://gitlab.com/neitsab/bastientraverse.com 
Clonage dans 'bastientraverse.com'...
avertissement : redirection vers https://gitlab.com/neitsab/bastientraverse.com.git/
remote: Enumerating objects: 953, done.
remote: Counting objects: 100% (953/953), done.
remote: Compressing objects: 100% (354/354), done.
remote: Total 953 (delta 432), reused 953 (delta 432), pack-reused 0
Réception d'objets: 100% (953/953), 1.21 Mio | 5.78 Mio/s, fait.
Résolution des deltas: 100% (432/432), fait.
Sous-module 'themes/even' (https://github.com/neitsab/hugo-theme-even) enregistré pour le chemin 'themes/even'
Clonage dans '/tmp/bastientraverse.com/themes/even'...
remote: Enumerating objects: 1712, done.        
remote: Total 1712 (delta 0), reused 0 (delta 0), pack-reused 1712        
Réception d'objets: 100% (1712/1712), 1.74 Mio | 4.03 Mio/s, fait.
Résolution des deltas: 100% (998/998), fait.
Chemin de sous-module 'themes/even' : 'dbb18e33a575da448a1a7167c9a2aea9170c88ac' extrait
/tmp % cd bastientraverse.com 
```

```go
/tmp/bastientraverse.com (git)-[main] % hugo server
panic: interface conversion: interface {} is []interface {}, not maps.Params

goroutine 1 [running]:
github.com/gohugoio/hugo/config/allconfig.fromLoadConfigResult({0x3ecd420, 0x528a040}, {0x3ed6198, 0xc000950a80}, {{0x3ecf3a8, 0xc000267600}, {0xc000b827b0, 0x1, 0x1}, {{0xc00005c024, ...}, ...}})
	/root/project/hugo/config/allconfig/allconfig.go:771 +0x1a96
github.com/gohugoio/hugo/config/allconfig.LoadConfig({{0x3ecd420, 0x528a040}, {0x3ed6198, 0xc000950a80}, {0x3ecf3a8, 0xc0002675c0}, {0x0, 0x0}, {0x288be78, 0x6}, ...})
	/root/project/hugo/config/allconfig/load.go:61 +0x4e5
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider.func1(0x276ff8?)
	/root/project/hugo/commands/commandeer.go:217 +0x338
github.com/bep/lazycache.(*Cache[...]).GetOrCreate(0x3ee09c0, 0x0, 0xc000807978?)
	/root/project/gomodcache/github.com/bep/lazycache@v0.2.0/lazycache.go:112 +0x12a
github.com/gohugoio/hugo/commands.(*rootCommand).ConfigFromProvider(0xc000266680?, 0x3ecf3a8?, {0x3ecf3a8, 0xc0002675c0})
	/root/project/hugo/commands/commandeer.go:193 +0x5e
github.com/gohugoio/hugo/commands.(*hugoBuilder).loadConfig(0xc000950b00, 0x6?, 0x1)
	/root/project/hugo/commands/hugobuilder.go:997 +0x3b6
github.com/gohugoio/hugo/commands.(*serverCommand).PreRun(0xc000940fa0, 0xc000266680, 0xc000266680?)
	/root/project/hugo/commands/server.go:604 +0x3f2
github.com/bep/simplecobra.(*Commandeer).init(0xc000266680)
	/root/project/gomodcache/github.com/bep/simplecobra@v0.4.0/simplecobra.go:92 +0xc5
github.com/bep/simplecobra.(*Commandeer).compile.func2(0xc000954200?, {0x2883f15?, 0x4?, 0x2883d41?})
	/root/project/gomodcache/github.com/bep/simplecobra@v0.4.0/simplecobra.go:119 +0x17
github.com/spf13/cobra.(*Command).execute(0xc000952900, {0x528a040, 0x0, 0x0})
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:968 +0xa36
github.com/spf13/cobra.(*Command).ExecuteC(0xc000952000)
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	/root/project/gomodcache/github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/bep/simplecobra.(*Exec).Execute(0xc0008a4d70, {0x3ec2298?, 0x528a040?}, {0xc000052050?, 0x100506901?, 0x0?})
	/root/project/gomodcache/github.com/bep/simplecobra@v0.4.0/simplecobra.go:155 +0xd4
github.com/gohugoio/hugo/commands.Execute({0xc000052050, 0x1, 0x1})
	/root/project/hugo/commands/commandeer.go:65 +0x2f9
main.main()
	/root/project/hugo/main.go:25 +0x56
```

I guess there must have been some breaking changes since the last time I updated this website, but this doesn't really me what those are.

Thanks for your consideration 🙏🏻

**Comment by neitsab** [comment]
I just tested with v119 and it ended in another panic, but v101 (the latest one I defined on Vercel) works fine.

**Comment by jmooring** [comment]
The panic is reproducible with v0.112.0 and later due to an error in the site configuration:

```text
[languages.fr]
languageCode = "fr"
languageName = "Français"
weight = 2

  [[languages.fr.params]]            <-- this should not be an array
  description = "Créer et partager"
```

The above should be:

```text
[languages.fr]
languageCode = "fr"
languageName = "Français"
weight = 2

  [languages.fr.params]
  description = "Créer et partager"
```

**Comment by neitsab** [comment]
Damn, thank you for pointing that out, I would have never found it by myself. I confirm that this single change resolves the panic.

A quick search for "hugo config array" didn't bring up any authoritative resources on that topic. I don't have a good handle on for what an array should be used for or not, and how it is specified (obviously here with a double bracket). Would you have some documentation to point me to?

In any case, feel free to close the issue.
Thanks a lot

**Comment by jmooring** [comment]
Please use the forum (https://discourse.gohugo.io/) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
