### ISSUE TITLE
Can't use `hugo new content` on folder path containing umlauts

### ISSUE THREAD

**Issue by SamusAranX** [gohugoio/hugo#11887]
I have a content folder structure that looks like this (abbreviated):
```
content/
├── _index.md
├── aachen
│   ├── 2024-01-07
│   │   ├── 2024-01-07.pdf
│   │   └── 2024-01-07.png
│   ├── 2024-01-14
│   │   ├── 2024-01-14.pdf
│   │   └── 2024-01-14.png
│   └── _index.md
└──düren
    ├── 2023-12-31
    │   ├── 2023-12-31.pdf
    │   └── 2023-12-31.png
    ├── 2024-01-07
    │   ├── 2024-01-07.pdf
    │   └── 2024-01-07.png
    ├── 2024-01-14
    │   ├── 2024-01-14.pdf
    │   └── 2024-01-14.png
    └── _index.md
```

Additionally, I created a new bundle archetype:
```
archetypes/
└── issue
    └── index.md
```

with `index.md` looking like this:

```
---
{{ $issueDate := time.AsTime .File.ContentBaseName -}}
{{- $issueDateISO := $issueDate | time.Format "2006-01-02" -}}
title: "{{ $issueDate | time.Format ":date_long" }}"
date: "{{ $issueDateISO }}"
thumbnail: "{{ $issueDateISO }}.png"
issue: "{{ $issueDateISO }}.pdf"
---

<a class="download" href="{{ $issueDateISO }}.pdf">
{{< figure "{{ $issueDateISO }}.png" "Klicke, um die Ausgabe zu lesen" >}}
</a>
```

The PDF and PNG files are generated and copied into my site's folder structure by a script that also runs `hugo new content --kind issue "content/<section>/<bundle>"` on every page bundle folder. In this example, this works great with all bundles in the `aachen` section, resulting in `index.md` files that look like this:

```
---
title: "7. Januar 2024"
date: "2024-01-07"
thumbnail: "2024-01-07.png"
issue: "2024-01-07.pdf"
---

<a class="download" href="2024-01-07.pdf">
{{< figure "2024-01-07.png" "Klicke, um die Ausgabe zu lesen" >}}
</a>
```

Once hugo is fed a path containing umlauts however, it crashes. In the console output, that manifests like this:

```
Content dir "<path>/content/aachen/2024-01-07" created
Content dir "<path>/content/aachen/2024-01-14" created
panic: [BUG] no Page found for "<path>/content/düren/2023-12-31/index.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0x140008e8300, {0x14000a6fe00, 0x58}, {0x14000a54dc0, 0xe})
	github.com/gohugoio/hugo/create/content.go:278 +0x238
github.com/gohugoio/hugo/create.(*contentBuilder).buildDir(0x140008e8300)
	github.com/gohugoio/hugo/create/content.go:181 +0x494
github.com/gohugoio/hugo/create.NewContent.func1()
	github.com/gohugoio/hugo/create/content.go:94 +0x118
github.com/gohugoio/hugo/create.NewContent(0x140008cf7c0, {0x16fc13530, 0x5}, {0x16fc13536, 0x1a}, 0x1)
	github.com/gohugoio/hugo/create/content.go:109 +0x498
github.com/gohugoio/hugo/commands.newNewCommand.func1({0x0?, 0x0?}, 0x0?, 0x0?, {0x14000115c80, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/new.go:60 +0x160
github.com/gohugoio/hugo/commands.(*simpleCommand).Run(0x0?, {0x103b36b78?, 0x104e10920?}, 0x0?, {0x14000115c80?, 0x0?, 0x0?})
	github.com/gohugoio/hugo/commands/commandeer.go:588 +0x48
github.com/bep/simplecobra.(*Commandeer).compile.func1(0x1400067c600?, {0x14000115c80?, 0x4?, 0x101ea4e9f?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:113 +0x54
github.com/spf13/cobra.(*Command).execute(0x140006b0600, {0x14000115c40, 0x4, 0x4})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0x840
github.com/spf13/cobra.(*Command).ExecuteC(0x140009c9800)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x344
github.com/spf13/cobra.(*Command).ExecuteContextC(...)
	github.com/spf13/cobra@v1.8.0/command.go:1048
github.com/bep/simplecobra.(*Exec).Execute(0x1400071ccc0, {0x103b36b78?, 0x104e10920?}, {0x1400004e080?, 0x14000086658?, 0x100234de8?})
	github.com/bep/simplecobra@v0.4.0/simplecobra.go:155 +0xb4
github.com/gohugoio/hugo/commands.Execute({0x1400004e080, 0x6, 0x6})
	github.com/gohugoio/hugo/commands/commandeer.go:65 +0x284
main.main()
	github.com/gohugoio/hugo/main.go:25 +0x70
```

The names of the sections are outside of my control and cannot be edited to not contain umlauts. Is there any other way to work around this?

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.121.2-6d5b44305eaa9d0a157946492a6f319da38de154+extended darwin/arm64 BuildDate=2024-01-05T12:21:15Z VendorInfo=brew
</pre>

### Does this issue reproduce with the latest release?
Yes

**Comment by SamusAranX** [comment]
As a workaround, I ended up modifying the script so it normalizes the paths in Python:

```sh
contentdir=$(python3 -c "from unicodedata import normalize; import sys; print(normalize(\"NFC\", sys.argv[1]))" "$contentdir")
```
