### ISSUE TITLE
Improve error message thrown by transform.ToMath

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#12990]
markdown (note the erroneous double-escape before "frac"):

```text
\[\\frac 1 2\]
```

> executing "_default/_markup/render-passthrough.html" at <_html_template_htmlescaper>: error calling _html_template_htmlescaper: not a function

This works fine:

```text
\[\frac 1 2\]
```

Another example that triggers the error:

```text
$$I = \frac{ 12 \text{V} }{ 4 \text{Ω} }$$
```

In this case, the `text{Ω}` bit is the the problem. This works fine:

```text
$$I = \frac{ 12 \text{V} }{ 4 \Omega }$$
```

Note that the KaTeX engine renders both of the above without error.

```text
\[\\frac 1 2\]

$$I = \frac{ 12 \text{V} }{ 4 \text{Ω} }$$
```

![image](https://github.com/user-attachments/assets/91073081-b73e-4b42-be4d-5c2ca7a8708d)

<details>
<summary>test case (the last three assertions need some work)</summary>

```go
func TestFoo(t *testing.T) {
	t.Parallel()

	files := `
-- hugo.toml --
disableKinds = ['home','rss','section','sitemap','taxonomy','term']
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]']]
inline = [['\(', '\)']]
-- layouts/_default/single.html --
{{ .Content }}
-- layouts/_default/_markup/render-passthrough.html --
{{- transform.ToMath .Inner (dict "displayMode" (eq .Type "block")) -}}
-- content/p1.md --
---
title: p1
---
\(\\frac 1 2\)
-- content/p2.md --
---
title: p2
---
\[\\frac 1 2\]
-- content/p3.md --
---
title: p3
---
\(I = \frac{ 12 \text{V} }{ 4 \text{Ω} }\)
-- content/p43.md --
---
title: p4
---
\[I = \frac{ 12 \text{V} }{ 4 \text{Ω} }\]
`

	b := hugolib.Test(t, files)

	b.AssertFileContent("public/p1/index.html", `<p><span class="katex"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mspace linebreak="newline"></mspace><mi>f</mi><mi>r</mi><mi>a</mi><mi>c</mi><mn>12</mn></mrow><annotation encoding="application/x-tex">\\frac 1 2</annotation></semantics></math></span></p>`)
	b.AssertFileContent("public/p2/index.html", `TBD`)
	b.AssertFileContent("public/p3/index.html", `TBD`)
	b.AssertFileContent("public/p4/index.html", `TBD`)
}
```
</details>

**Comment by bep** [comment]
We need to fix this, but I suspect that this workaround should give a better error message:

>{{- transform.ToMath.Value .Inner (dict "displayMode" (eq .Type "block")) -}}

**Comment by bep** [comment]
>{{- transform.ToMath .Inner (dict "displayMode" (eq .Type "block")) -}}


We should fix this, but you can do:

```handlebars
{{ $result := transform.ToMath .Inner (dict "displayMode" (eq .Type "block")) }}
{{ with $result.Error }}
// Print error.
{{ with else  $result.Value }}
{ { end }}
```

... I'm not totally sure I got the with else syntax correct.

**Comment by jmooring** [comment]
This:

```text
{{ with transform.ToMath `\\frac 1 2` (dict "displayMode" true) }}
  {{ with .Err }}
    {{ errorf "%s" . }}
  {{ else }}
    {{ . }}
  {{ end }}
{{ end }}
```

Throws this error:

```text
ERROR not a function
```

So... that one's not much help either.

**Comment by bep** [comment]
>So... that one's not much help either.

Well, it's more ... to the point.

**Comment by bep** [comment]
I have done some investigating, and the very short `not a function` error message is thrown by `katex.renderToString`, which smells like an upstream parser bug.

```
at useStrictBehavior (function.mjs:407:51)\n    at handler (function.mjs:6942:70)\n    at callFunction (function.mjs:13933:21)\n    at parseFunction (function.mjs:13919:19)\n    at parseGroup (function.mjs:14206:23)\n    at parseAtom (function.mjs:13796:23)\n    at parseExpression (function.mjs:13686:25)\n    at parse (function.mjs:13635:26)\n    at parseTree2 (function.mjs:14376:23)\n    at renderToDomTree2 (function.mjs:14425:18)\n    at renderToString2 (function.mjs:14406:18)\n    at render3 (function.mjs:14532:26)\n    at readInput (function.mjs:41:13)\n    at <anonymous> (function.mjs:14535:3)\n    at <anonymous> (function.mjs:14536:1)\n
```

**Comment by jmooring** [comment]
Closing this.

I'm in the process of improving the `transform.ToMath` examples, including the passthrough render hook example, to display the value returned by `.Err`.
