### ISSUE TITLE
Improve RST error handling

### ISSUE THREAD

**Issue by kode54** [gohugoio/hugo#2697]
Running 0.17 on macOS Sierra 10.12.1, built from source using Homebrew, against Go v1.7.3, it produces the following output:

```
$ hugo
Started building sites ...
ERROR: 2016/11/15 23:29:20 content.go:593: exit status 1
ERROR: 2016/11/15 23:29:20 content.go:593: exit status 1
panic: runtime error: slice bounds out of range

goroutine 183 [running]:
panic(0x64c980, 0xc42000c100)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/spf13/hugo/helpers.getRstContent(0xc42046a1a0, 0xc9, 0xd0, 0x3, 0x1, 0x6c0540)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/helpers/content.go:602 +0x53b
github.com/spf13/hugo/helpers.RenderBytes(0xc4204b8000, 0xc4204b8000, 0x3, 0xc42046a1a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/helpers/content.go:390 +0x153
github.com/spf13/hugo/hugolib.(*Page).renderContent(0xc4200e0500, 0xc42046a1a0, 0xc9, 0xd0, 0xb, 0xb, 0x9f0570)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/page.go:383 +0x209
github.com/spf13/hugo/hugolib.commonConvert(0xc4200e0500, 0x9fe200, 0xc4203e5c70, 0x20, 0x623860, 0x621401, 0xc4202b00a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_page.go:125 +0x183
github.com/spf13/hugo/hugolib.rstHandler.PageConvert(0x0, 0x0, 0x0, 0xc4200e0500, 0x9fe200, 0xc4203e5c70, 0xc4202b00a0, 0xc42048ae88, 0xe2b38, 0xc42035d859)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_page.go:95 +0x3f
github.com/spf13/hugo/hugolib.(*rstHandler).PageConvert(0xc4201b1fe0, 0xc4200e0500, 0x9fe200, 0xc4203e5c70, 0xc4202b00b0, 0xc42048aee8, 0xe2a18, 0x9fa7e0)
	<autogenerated>:152 +0x82
github.com/spf13/hugo/hugolib.(*MetaHandle).Convert(0xc4202b0000, 0x6e67c0, 0xc4200e0500, 0xc4203f0000, 0xc4205145a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_meta.go:77 +0xcc
github.com/spf13/hugo/hugolib.pageConverter(0xc4203f0000, 0xc420514600, 0xc4205145a0, 0xc4202f8260)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/site.go:1231 +0x112
created by github.com/spf13/hugo/hugolib.(*Site).convertSource
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/site.go:1162 +0x1ae
panic: runtime error: slice bounds out of range

goroutine 181 [running]:
panic(0x64c980, 0xc42000c100)
	/usr/local/Cellar/go/1.7.3/libexec/src/runtime/panic.go:500 +0x1a1
github.com/spf13/hugo/helpers.getRstContent(0xc4201d01a0, 0xcd, 0xd0, 0x3, 0x1, 0x6c0540)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/helpers/content.go:602 +0x53b
github.com/spf13/hugo/helpers.RenderBytes(0xc42043c000, 0xc42043c000, 0x3, 0xc4201d01a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/helpers/content.go:390 +0x153
github.com/spf13/hugo/hugolib.(*Page).renderContent(0xc420394000, 0xc4201d01a0, 0xcd, 0xd0, 0xb, 0xb, 0x9f0570)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/page.go:383 +0x209
github.com/spf13/hugo/hugolib.commonConvert(0xc420394000, 0x9fe200, 0xc4203e5c70, 0x20, 0x623860, 0x621401, 0xc4203dc0a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_page.go:125 +0x183
github.com/spf13/hugo/hugolib.rstHandler.PageConvert(0x0, 0x0, 0x0, 0xc420394000, 0x9fe200, 0xc4203e5c70, 0xc4203dc0a0, 0xc420487e88, 0xe2b38, 0xc42035d73d)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_page.go:95 +0x3f
github.com/spf13/hugo/hugolib.(*rstHandler).PageConvert(0xc4201b1fe0, 0xc420394000, 0x9fe200, 0xc4203e5c70, 0xc4203dc0b0, 0xc420487ee8, 0xe2a18, 0x9fa7e0)
	<autogenerated>:152 +0x82
github.com/spf13/hugo/hugolib.(*MetaHandle).Convert(0xc4203dc040, 0x6e67c0, 0xc420394000, 0xc4203f0000, 0xc4205145a0)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/handler_meta.go:77 +0xcc
github.com/spf13/hugo/hugolib.pageConverter(0xc4203f0000, 0xc420514600, 0xc4205145a0, 0xc4202f8260)
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/site.go:1231 +0x112
created by github.com/spf13/hugo/hugolib.(*Site).convertSource
	/private/tmp/hugo-20161115-35256-nr0s4d/hugo-0.17/src/github.com/spf13/hugo/hugolib/site.go:1162 +0x1ae
```

My site's entire source tree is here:

https://f.losno.co/kuroshi.moe.tar.bz2

Nothing terribly secret or special, and all static content except for the favicon and touch icon are hosted separate from this source tree.

Also included is the hugo-bootstrap theme. I'm open to suggestions on a better theme for this, since I kind of want something that also displays at least a thumbnail of articles' images on the main index, instead of the mess that's up now:

https://kuroshi.moe/

**Comment by kode54** [comment]
Adding a note. It appears the error may be with rst2html.py, as that fails to even run on my system, even though I installed it with ```brew install docutils```...

```
$ rst2html.py
Traceback (most recent call last):
  File "/usr/local/bin/rst2html.py", line 17, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core
```

**Comment by davidkassa** [comment]
I'm on Windows receiving the same error now but built from source.

**Comment by bep** [comment]
This issue has been automatically marked as stale because it has not been commented on for at least six months.

The resources of the Hugo team are limited, and so we are asking for your help.

If this is a **bug** and you can still reproduce this error on the <code>master</code> branch, please reply with all of the information you have about it in order to keep the issue open.

If this is a **feature request**, and you feel that it is still relevant and valuable, please tell us why.

This issue will automatically be closed in the near future if no further activity occurs. Thank you for all your contributions.
