### ISSUE TITLE
SIGSEGV in "hugo server" after file change

### ISSUE THREAD

**Issue by marklwells** [gohugoio/hugo#3736]
Hugo version:   v0.25.1 darwin/amd64 BuildDate: 2017-07-24T20:19:46-05:00
(Happened with v0.25, also.)

OS Version:  macOS Sierra, 10.12.6

go version:  go1.8.3 darwin/amd64

When I run "hugo server", the program launches fine and I can see the site.  However, when I change a file, hugo crashes with a stack trace which you can see below. 

I have been updating my website over the last several weeks and this never happened.  Today it started happening on every change.  I don't know what changed in my site to trigger this bug.  Generating the entire site using just "hugo" works fine.

Thanks for the work you all put into this product.

```
$ hugo server --verboseLog -w
Started building sites ...
Built site for language en:
0 draft content
0 future content
0 of 5 expired rendered
72 regular pages created
86 other pages created
0 non-page files copied
8 paginator pages created
29 tags created
total in 26 ms
Watching for changes in /Users/mwells/Java/Personal/mwells-org/{data,content,layouts,static}
Serving pages from memory
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site
2017-07-24 21:56 -0500
Source changed "/Users/mwells/Java/Personal/mwells-org/content/reel-mowers/choosing-a-reel-mower.md": WRITE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x338 pc=0x1627545]

goroutine 248 [running]:
text/template.errRecover(0xc423635450)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:140 +0x1ec
panic(0x171e740, 0x1ba4a20)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/gohugoio/hugo/hugolib.(*Page).Parent(0x0, 0x0)
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site_sections.go:44 +0x5
reflect.Value.call(0x17cf600, 0xc425393a68, 0x9e93, 0x17d3dc1, 0x4, 0x1bd5c18, 0x0, 0x0, 0x100d15a, 0xc423634348, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f
reflect.Value.Call(0x17cf600, 0xc425393a68, 0x9e93, 0x1bd5c18, 0x0, 0x0, 0x16f7740, 0x16f7740, 0xc425305510)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4
text/template.(*state).evalCall(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0x17cf600, 0xc425393a68, 0x9e93, 0x1b64880, 0xc42168a780, 0xc42239c1e4, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:668 +0x51f
text/template.(*state).evalField(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0xc42239c1e4, 0x6, 0x1b64880, 0xc42168a780, 0xc421096ac0, 0x1, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:558 +0xe18
text/template.(*state).evalFieldChain(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0x17cf600, 0xc425393a68, 0x96, 0x1b64880, 0xc42168a780, 0xc421096ab0, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:526 +0x22b
text/template.(*state).evalFieldNode(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0xc42168a780, 0xc421096ac0, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:490 +0x118
text/template.(*state).evalCommand(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0xc42168a750, 0x0, 0x0, 0x0, 0x4, 0x3, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:428 +0x837
text/template.(*state).evalPipeline(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0xc421688370, 0x0, 0x0, 0x88d)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:406 +0xf2
text/template.(*state).walkIfOrWith(0xc423634d90, 0xa, 0x17cf600, 0xc425393a68, 0x96, 0xc421688370, 0xc42168a7b0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:261 +0xbc
text/template.(*state).walk(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0x1b64940, 0xc4224d9500)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:237 +0x377
text/template.(*state).walk(0xc423634d90, 0x17cf600, 0xc425393a68, 0x96, 0x1b649a0, 0xc42168a6f0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:240 +0x139
text/template.(*state).walkTemplate(0xc423635200, 0x17cf600, 0xc425393a68, 0x96, 0xc42109a580)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:389 +0x267
text/template.(*state).walk(0xc423635200, 0x17cf600, 0xc424b839f0, 0x196, 0x1b64be0, 0xc42109a580)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:245 +0x226
text/template.(*state).walk(0xc423635200, 0x17cf600, 0xc424b839f0, 0x196, 0x1b649a0, 0xc421099d70)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:240 +0x139
text/template.(*state).walkRange.func1(0x16e5c60, 0xc4253939c0, 0x82, 0x17cf600, 0xc424b839f0, 0x196)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:327 +0x136
text/template.(*state).walkRange(0xc423635200, 0x17d0480, 0xc4251e4c00, 0x16, 0xc4224d92c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:336 +0x34e
text/template.(*state).walk(0xc423635200, 0x17d0480, 0xc4251e4c00, 0x16, 0x1b64b20, 0xc4224d92c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:243 +0x4f1
text/template.(*state).walk(0xc423635200, 0x17d0480, 0xc4251e4c00, 0x16, 0x1b649a0, 0xc4216851d0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:240 +0x139
text/template.(*state).walkTemplate(0xc4236353d0, 0x17d0480, 0xc4251e4c00, 0x16, 0xc422cc7000)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:389 +0x267
text/template.(*state).walk(0xc4236353d0, 0x17d0480, 0xc4251e4c00, 0x16, 0x1b64be0, 0xc422cc7000)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:245 +0x226
text/template.(*state).walk(0xc4236353d0, 0x17d0480, 0xc4251e4c00, 0x16, 0x1b649a0, 0xc422cc9ad0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:240 +0x139
text/template.(*Template).execute(0xc422cbe280, 0x1b5a020, 0xc420d8da40, 0x17d0480, 0xc4251e4c00, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:195 +0x20a
text/template.(*Template).Execute(0xc422cbe280, 0x1b5a020, 0xc420d8da40, 0x17d0480, 0xc4251e4c00, 0xc420203f80, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/text/template/exec.go:178 +0x53
html/template.(*Template).Execute(0xc422cc9fb0, 0x1b5a020, 0xc420d8da40, 0x17d0480, 0xc4251e4c00, 0x7, 0xc424389070)
	/usr/local/Cellar/go/1.8.3/libexec/src/html/template/template.go:120 +0x8c
github.com/gohugoio/hugo/tpl.(*TemplateAdapter).Execute(0xc4253923f0, 0x1b5a020, 0xc420d8da40, 0x17d0480, 0xc4251e4c00, 0xc4253923f0, 0x2)
	<autogenerated>:3 +0x75
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts(0xc42010e780, 0x17d96f2, 0x7, 0x17d0480, 0xc4251e4c00, 0x1b5a020, 0xc420d8da40, 0xc424389000, 0x30, 0x40, ...)
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site.go:1975 +0xb8
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0xc42010e780, 0xc422bfcee0, 0xf, 0xc425381c40, 0x19, 0xc4251e4c00, 0xc424389000, 0x30, 0x40, 0x0, ...)
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site.go:1915 +0xff
github.com/gohugoio/hugo/hugolib.(*Site).renderPaginator(0xc42010e780, 0xc422a89200, 0x15, 0xc424f9f460)
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site_render.go:189 +0x7dc
github.com/gohugoio/hugo/hugolib.pageRenderer(0xc42010e780, 0xc424f2cae0, 0xc424f2ca80, 0xc424f2b790)
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site_render.go:127 +0x82e
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
	/private/tmp/hugo-20170710-9452-1tz7t46/hugo-0.25.1/src/github.com/gohugoio/hugo/hugolib/site_render.go:44 +0x156
```

**Comment by marklwells** [comment]
This exception only occurs when some pages are modified.  I use the relatively new subsection feature in this site.

**Comment by bep** [comment]
The panic itself is fixed in https://github.com/gohugoio/hugo/commit/61bb3ccab3a552c4b80ffb5370714598660b7b37

It will not solve your problem, but makes it easier to debug (clearer error message). You use a object that is `nil`in a template; you need to wrap it in `with` or use `if` to check that it is set.

**Comment by marklwells** [comment]
Thank you!
