### ISSUE TITLE
Shortcode panic with redefinition of HTML output format

### ISSUE THREAD

**Issue by bep** [gohugoio/hugo#4114]
```bash
panic: Shortcode "HAHAHUGOSHORTCODE-1HBHB" could not be found

goroutine 376 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).contentShortcodesForOutputFormat(0xc4210adcc0, 0x1a06edf, 0x4, 0x1a081a7, 0x4, 0x1a07a63, 0x4, 0xc420377d0c, 0x3, 0x1a05325, ...)
	/Users/bep/go/src/github.com/gohugoio/hugo/hugolib/shortcode.go:395 +0x659
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).updateDelta(0xc4210adcc0, 0x1a06edf)
	/Users/bep/go/src/github.com/gohugoio/hugo/hugolib/shortcode.go:354 +0xb4
github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender.func1(0xc420104f00, 0xc421397f40, 0xc421536300, 0xc421a0ba30)
	/Users/bep/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:517 +0x907
created by github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender
	/Users/bep/go/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:508 +0xd3
```

**Comment by bep** [comment]
Seems the issue is this:

* If you redefine `HTML` with a new suffix.
* But you only define `outputs` for the home page.
* The `page` kind will default to the (internal) `HTML` output type, which has a different suffix...

**Comment by bep** [comment]
The workaround for this is, if you redefine HTML or any internal output format, to make sure you have a `outputs` definition for every Kind.
