### ISSUE TITLE
Hugo fails if "+" is in MediaType

### ISSUE THREAD

**Issue by dan1wang** [gohugoio/hugo#4729]
Hugo does like it if you have "+" sign in mediaType

this config.toml is OK:

```
baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[mediaTypes]
  [mediaTypes."application/xml"]
    suffix = "abc"
  [mediaTypes."image/svg"]
    suffix = "svg"
  [mediaTypes."image/bpm"]
    suffix = "bpm"

[outputFormats]
  [outputFormats.raw]
    mediaType = "application/xml"
    isPlainText = false
  [outputFormats.svg]
    mediaType = "image/svg"
    isPlainText = true

[outputs]
  home = ["html"]
  page = ["html"]
  post = ["html"]

```

But this one leads to failure:

```
baseurl = "/"
languageCode = "en-us"
title = "Homepage"

[mediaTypes]
  [mediaTypes."application/xml"]
    suffix = "abc"
  [mediaTypes."image/svg+xml"]
    suffix = "svg"
  [mediaTypes."image/bpm"]
    suffix = "bpm"

[outputFormats]
  [outputFormats.raw]
    mediaType = "application/xml"
    isPlainText = false
  [outputFormats.svg]
    mediaType = "image/svg+xml"
    isPlainText = true

[outputs]
  home = ["html"]
  page = ["html"]
  post = ["html"]

```

The error message is

```
[20:30:55] Error: Hugo build failed
    at formatError (D:\YM\Documents\GitHub\cms1\node_modules\gulp\bin\gulp.js:169:10)
    at Gulp.<anonymous> (D:\YM\Documents\GitHub\cms1\node_modules\gulp\bin\gulp.js:195:15)
    at emitOne (events.js:116:13)
    at Gulp.emit (events.js:211:7)
    at Gulp.Orchestrator._emitTaskDone (D:\YM\Documents\GitHub\cms1\node_modules\orchestrator\index.js:264:8)
    at D:\YM\Documents\GitHub\cms1\node_modules\orchestrator\index.js:275:23
    at finish (D:\YM\Documents\GitHub\cms1\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (D:\YM\Documents\GitHub\cms1\node_modules\orchestrator\lib\runTask.js:29:3)
    at ChildProcess.<anonymous> (D:/YM/Documents/GitHub/cms1/gulpfile.babel.js:95:7)
    at emitTwo (events.js:126:13)
```

**Comment by bep** [comment]
if you run Hugo from outside Gulp, you will get a bette error message, surely telling you that "+" is not supported in the media type name.

**Comment by dan1wang** [comment]
[hugo/media/mediaType.go](https://github.com/gohugoio/hugo/blob/master/media/mediaType.go) has the following code. I am not a programming expert, but the code looks like "+" should be supported?

```
// FromString creates a new Type given a type sring on the form MainType/SubType and
// an optional suffix, e.g. "text/html" or "text/html+html".
func FromString(t string) (Type, error) {
	t = strings.ToLower(t)
	parts := strings.Split(t, "/")
	if len(parts) != 2 {
		return Type{}, fmt.Errorf("cannot parse %q as a media type", t)
	}
	mainType := parts[0]
	subParts := strings.Split(parts[1], "+")

	subType := subParts[0]
	var suffix string

	if len(subParts) == 1 {
		suffix = subType
	} else {
		suffix = subParts[1]
	}

	return Type{MainType: mainType, SubType: subType, Suffix: suffix, Delimiter: defaultDelimiter}, nil
}
```

**Comment by bep** [comment]
But what does the error message you get from Hugo say?

**Comment by dan1wang** [comment]
I don't know how to use hugo command. I use Netlify's CMS starter kit, and the only command I know is "npm start"

**Comment by kevingimbel** [comment]
@dan1wang You can look into the `package.json` file to see which command is run. The section in the `package.json` is named `scripts`. 

Try to run hugo standalone with the following command in a terminal.

```sh
$ hugo serve -v
```

This command starts the hugo server (which reloads your page on change) and `-v` enables verbose output.

**Comment by dan1wang** [comment]
I got this error message

> Error: Error building site: media type keys cannot contain any '+' chars. Valid example is "text/css"

You are correct "+" is not supported

https://github.com/gohugoio/hugo/blob/47fdfd5196cd24a23b30afe1d88969ffb413ab59/media/mediaType.go#L155-L158
