### ISSUE TITLE
duplicate permalinks key cause "nil pointer dereference"

### ISSUE THREAD

**Issue by nizsheanez** [gohugoio/hugo#4902]
Config to reproduce:
```
[permalinks]
  products = "/products/:title/"
  products = "/products/:title/"
```

Hugo Version: v0.42.2 darwin/amd64

Trace:
```
Failed to reload config: While parsing config: (27, 3): The following key was defined twice: permalinks.products
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1897fd5]

goroutine 204 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc425f77540, 0xc420164280, 0xc42606e330, 0xc42000f408)
	/private/tmp/hugo-20180628-63389-1hyhd9w/hugo-0.42.2/src/github.com/gohugoio/hugo/commands/hugo.go:685 +0x2e5
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
	/private/tmp/hugo-20180628-63389-1hyhd9w/hugo-0.42.2/src/github.com/gohugoio/hugo/commands/hugo.go:674 +0x29e
```

**Comment by moorereason** [comment]
@nizsheanez,
I'm unable to reproduce this panic in the latest Hugo.  Can you confirm that it's still an issue?
