### ISSUE TITLE
v0.52/extended SIGSEGV while frequently minifying js files

### ISSUE THREAD

**Issue by mr-moon** [gohugoio/hugo#5530]
```
$ ./hugo server --verboseLog -w

                   | RU  | ET
+------------------+-----+-----+
  Pages            |  54 |   6
  Paginator pages  |   0 |   0
  Non-page files   |  24 |   0
  Static files     | 695 | 695
  Processed images |   0 |   0
  Aliases          |   1 |   1
  Sitemaps         |   2 |   1
  Cleaned          |   0 |   0

Total in 995 ms
Watching for changes in /Users/moon/Stark/stark.ee/{assets,content,data,i18n,layouts,static}
Watching for config changes in /Users/moon/Stark/stark.ee/config.toml
Serving pages from memory
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop

Change detected, rebuilding site
2018-12-17 15:03:04.034 +0200
Total in 19 ms

Change detected, rebuilding site
2018-12-17 15:03:07.033 +0200
Total in 23 ms

Change detected, rebuilding site
2018-12-17 15:03:09.037 +0200
Total in 20 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x495e21e]

goroutine 207 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc00024a300, 0xc002251460, 0xc001cce290, 0xc008b22520, 0x1, 0x1, 0xc0023e0630)
        /hugo/commands/hugo.go:796 +0x35e
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc002251460, 0xc00024a300, 0xc001cce290, 0xc0023e0630)
        /hugo/commands/hugo.go:730 +0x1d8
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /hugo/commands/hugo.go:726 +0x273
```

The file is then used in template as:
```
{{ $core := resources.Get "js/core.js" | resources.Minify }}
<script type="text/javascript" src="{{ $core.Permalink }}"></script>
```

And my `env` is:
```
Hugo Static Site Generator v0.52/extended darwin/amd64 BuildDate: 2018-11-28T14:58:25Z
GOOS="darwin"
GOARCH="amd64"
GOVERSION="go1.11"
```

**Comment by bep** [comment]
I doubt there is a connection between minification and this issue. I suspect there is some kind of race in situations where you get "many change events" -- but I cannot look into that without seeing your full build setup.

**Comment by mr-moon** [comment]
Shared a repo with you @bep on bitbucket. It's `mr-moon/stark.git`
