### ISSUE TITLE
0.56 Out of memory on raspberry

### ISSUE THREAD

**Issue by gj52** [gohugoio/hugo#6119]
Running Hugo 0.56 runs out of memory on Raspberry Raspbian with 1GB RAM
Linux pi3 4.19.50-v7+ #896 SMP Thu Jun 20 16:11:44 BST 2019 armv7l GNU/Linux

-- added log

Building sites … WARN 2019/07/27 15:15:33 Page's .URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url.
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf71828, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x5c
runtime.sysMap(0x38c00000, 0x2c00000, 0x1cfa978)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xac
runtime.(*mheap).sysAlloc(0x1cead40, 0x2810000, 0x175, 0x35e10)
        /usr/local/go/src/runtime/malloc.go:633 +0x180
runtime.(*mheap).grow(0x1cead40, 0x1408, 0x0)
        /usr/local/go/src/runtime/mheap.go:1222 +0x2c
runtime.(*mheap).allocSpanLocked(0x1cead40, 0x1408, 0x1cfa988, 0x0)
        /usr/local/go/src/runtime/mheap.go:1150 +0x3e8
runtime.(*mheap).alloc_m(0x1cead40, 0x1408, 0x3f2f0101, 0x66bd12a0)
        /usr/local/go/src/runtime/mheap.go:977 +0xd0
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x3c
runtime.(*mheap).alloc(0x1cead40, 0x1408, 0x1010101, 0x2)
        /usr/local/go/src/runtime/mheap.go:1047 +0x60
runtime.largeAlloc(0x280fc8c, 0x60101, 0x36738000)
        /usr/local/go/src/runtime/malloc.go:1055 +0x7c
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x38
runtime.systemstack(0x28645a0)
        /usr/local/go/src/runtime/asm_arm.s:354 +0x84
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

goroutine 137 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_arm.s:298 +0x4 fp=0x33cf6bc sp=0x33cf6b8 pc=0x6c488
runtime.mallocgc(0x280fc8c, 0xdab290, 0x1, 0x33cf73c)
        /usr/local/go/src/runtime/malloc.go:949 +0x894 fp=0x33cf720 sp=0x33cf6bc pc=0x1b6c4
runtime.makeslice(0xdab290, 0x280fc8c, 0x280fc8c, 0xdab050)
        /usr/local/go/src/runtime/slice.go:49 +0x70 fp=0x33cf734 sp=0x33cf720 pc=0x56458
bytes.makeSlice(0x280fc8c, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:232 +0x58 fp=0x33cf748 sp=0x33cf734 pc=0xed5c0
bytes.(*Buffer).grow(0xdbf3da0, 0x20a15f8, 0xdab050)
        /usr/local/go/src/bytes/buffer.go:145 +0x150 fp=0x33cf76c sp=0x33cf748 pc=0xecf28
bytes.(*Buffer).Write(0xdbf3da0, 0x36738000, 0x20a15f8, 0x20a2000, 0x1291401, 0xdab050, 0x3daff8c)
        /usr/local/go/src/bytes/buffer.go:175 +0xdc fp=0x33cf780 sp=0x33cf76c pc=0xed224
fmt.Fprint(0x1267b08, 0xdbf3da0, 0x33cf7e4, 0x1, 0x1, 0x3daff01, 0x2d5ee00, 0x0)
        /usr/local/go/src/fmt/print.go:234 +0x68 fp=0x33cf7b0 sp=0x33cf780 pc=0xdfbe4
text/template.(*state).printValue(0x33cfa04, 0x1279a68, 0x2d5ef80, 0xdab050, 0x3daff8c, 0x98)
        /usr/local/go/src/text/template/exec.go:941 +0xac fp=0x33cf7fc sp=0x33cf7b0 pc=0x18eaa0
text/template.(*state).walk(0x33cfa04, 0xe6c850, 0x3ac8300, 0x194, 0x1279a68, 0x2d5ef80)
        /usr/local/go/src/text/template/exec.go:256 +0x430 fp=0x33cf840 sp=0x33cf7fc pc=0x188028
text/template.(*state).walk(0x33cfa04, 0xe6c850, 0x3ac8300, 0x194, 0x1279bd0, 0x2d5e7e0)
        /usr/local/go/src/text/template/exec.go:262 +0xec fp=0x33cf884 sp=0x33cf840 pc=0x187ce4
text/template.(*state).walkRange.func1(0xdaa540, 0x1cf9620, 0x82, 0xe6c850, 0x3ac8300, 0x194)
        /usr/local/go/src/text/template/exec.go:349 +0x108 fp=0x33cf8a8 sp=0x33cf884 pc=0x197200
text/template.(*state).walkRange(0x3d31a04, 0xf15160, 0x385c060, 0x16, 0x2d66a00)
        /usr/local/go/src/text/template/exec.go:358 +0x420 fp=0x33cf93c sp=0x33cf8a8 pc=0x188d28
text/template.(*state).walk(0x3d31a04, 0xf15160, 0x385c060, 0x16, 0x1279c70, 0x2d66a00)
        /usr/local/go/src/text/template/exec.go:265 +0x3a0 fp=0x33cf980 sp=0x33cf93c pc=0x187f98
text/template.(*state).walk(0x33cfa04, 0xf15160, 0x385c060, 0x16, 0x1279bd0, 0x2ec34c0)
        /usr/local/go/src/text/template/exec.go:262 +0xec fp=0x33cf9c4 sp=0x33cf980 pc=0x187ce4
text/template.(*state).walkTemplate(0x3d31aec, 0xf15160, 0x385c060, 0x16, 0x2d77360)
        /usr/local/go/src/text/template/exec.go:412 +0x184 fp=0x33cfa28 sp=0x33cf9c4 pc=0x18919c
text/template.(*state).walk(0x3d31aec, 0xf15160, 0x385c060, 0x16, 0x1279cc0, 0x2d77360)
        /usr/local/go/src/text/template/exec.go:267 +0x19c fp=0x33cfa6c sp=0x33cfa28 pc=0x187d94
text/template.(*state).walk(0x33cfaec, 0xf15160, 0x385c060, 0x16, 0x1279bd0, 0x2d76ea0)
        /usr/local/go/src/text/template/exec.go:262 +0xec fp=0x33cfab0 sp=0x33cfa6c pc=0x187ce4
text/template.(*Template).execute(0x2e29620, 0x1267b08, 0xdbf3da0, 0xf15160, 0x385c060, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:217 +0x140 fp=0x33cfb10 sp=0x33cfab0 pc=0x1877c0
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:200
html/template.(*Template).Execute(0x2d77520, 0x1267b08, 0xdbf3da0, 0xf15160, 0x385c060, 0x126ee01, 0x126ee40)
        /usr/local/go/src/html/template/template.go:122 +0x6c fp=0x33cfb30 sp=0x33cfb10 pc=0x202b00
github.com/gohugoio/hugo/tpl.(*TemplateAdapter).Execute(0x45d1b00, 0x1267b08, 0xdbf3da0, 0xf15160, 0x385c060, 0x0, 0x0)
        /root/project/hugo/tpl/template.go:163 +0x90 fp=0x33cfb78 sp=0x33cfb30 pc=0x730210
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts(0x2b9e540, 0xf1c4fe, 0x4, 0xf1b3f6, 0x4, 0xf15160, 0x385c060, 0x1267b08, 0xdbf3da0, 0x3bb2380, ...)
        /root/project/hugo/hugolib/site.go:1724 +0x70 fp=0x33cfbc8 sp=0x33cfb78 pc=0x890350
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0x2b9e540, 0x2afc3c8, 0x3a8ae8c, 0x15, 0x3ba6a20, 0x2c, 0x385c060, 0x3bb2380, 0x10, 0x10, ...)
        /root/project/hugo/hugolib/site.go:1640 +0x110 fp=0x33cfe48 sp=0x33cfbc8 pc=0x88fde4
github.com/gohugoio/hugo/hugolib.pageRenderer(0x3c6fe20, 0x2b9e540, 0x3234c40, 0x37a36c0, 0x3cea010)
        /root/project/hugo/hugolib/site_render.go:152 +0x428 fp=0x33cffd4 sp=0x33cfe48 pc=0x892708
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:868 +0x4 fp=0x33cffd4 sp=0x33cffd4 pc=0x6e1b0
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /root/project/hugo/hugolib/site_render.go:73 +0x104

goroutine 1 [chan send]:
github.com/gohugoio/hugo/hugolib.(*Site).renderPages(0x2b9e540, 0x3c6fe20, 0x0, 0x0)
        /root/project/hugo/hugolib/site_render.go:90 +0x1ec
github.com/gohugoio/hugo/hugolib.(*Site).render(0x2b9e540, 0x3c6fe20, 0x0, 0x0)
        /root/project/hugo/hugolib/site.go:1163 +0x44
github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0x2bce480, 0x30cd8e0, 0x33cdc68, 0x18)
        /root/project/hugo/hugolib/hugo_sites_build.go:308 +0x2fc
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build.func4()
        /root/project/hugo/hugolib/hugo_sites_build.go:127 +0x2c
runtime/trace.WithRegion(0x1276820, 0x30cdf40, 0xf23f7d, 0x6, 0x33cdd04)
        /usr/local/go/src/runtime/trace/annotation.go:137 +0xe0
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0x2bce480, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /root/project/hugo/hugolib/hugo_sites_build.go:129 +0x588
github.com/gohugoio/hugo/commands.(*commandeer).buildSites(...)
        /root/project/hugo/commands/hugo.go:707
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild.func3(0x0, 0x0)
        /root/project/hugo/commands/hugo.go:318 +0x4c
github.com/gohugoio/hugo/commands.(*commandeer).fullBuild(0x2ab7b90, 0x0, 0x0)
        /root/project/hugo/commands/hugo.go:330 +0x12c
github.com/gohugoio/hugo/commands.(*commandeer).build(0x2ab7b90, 0x0, 0x0)
        /root/project/hugo/commands/hugo.go:479 +0xc0
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0x2a78c80, 0x2a53580, 0x0, 0x7, 0x0, 0x0)
        /root/project/hugo/commands/commands.go:162 +0xb0
github.com/spf13/cobra.(*Command).execute(0x2a78c80, 0x2824148, 0x7, 0x7, 0x2a78c80, 0x2824148)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:762 +0x360
github.com/spf13/cobra.(*Command).ExecuteC(0x2a78c80, 0x2ab2138, 0x2, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.4-0.20190321000552-67fc4837d267/command.go:850 +0x234
github.com/gohugoio/hugo/commands.Execute(0x2824148, 0x7, 0x7, 0x40770, 0x28320b0, 0x0, 0x0)
        /root/project/hugo/commands/hugo.go:89 +0x8c
main.main()
        /root/project/hugo/main.go:23 +0x58

goroutine 7 [select]:
go.opencensus.io/stats/view.(*worker).start(0x297a180)
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:154 +0xb0
created by go.opencensus.io/stats/view.init.0
        /go/pkg/mod/go.opencensus.io@v0.22.0/stats/view/worker.go:32 +0x48

goroutine 8 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/go/src/runtime/sigqueue.go:139 +0x130
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:23 +0x14
created by os/signal.init.0
        /usr/local/go/src/os/signal/signal_unix.go:29 +0x30

goroutine 136 [runnable]:
bytes.(*Buffer).WriteString(0x3378ea0, 0xb0f2000, 0x87a9c, 0x76f82a30, 0x0, 0x3744298)
        /usr/local/go/src/bytes/buffer.go:183 +0x110
html/template.processURLOnto(0xb0f2000, 0x87a9c, 0x1, 0x3378ea0, 0x87a9c)
        /usr/local/go/src/html/template/url.go:140 +0x388
html/template.urlProcessor(0x3a2f701, 0x37a7b30, 0x1, 0x1, 0x3378e8c, 0x23114)
        /usr/local/go/src/html/template/url.go:82 +0x8c
html/template.urlNormalizer(0x37a7b30, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/html/template/url.go:71 +0x34
reflect.Value.call(0xd85db0, 0xffc818, 0x13, 0xf1b276, 0x4, 0x3c1cdc0, 0x1, 0x1, 0x31ac1c0, 0x2842b40, ...)
        /usr/local/go/src/reflect/value.go:447 +0x3a4
reflect.Value.Call(0xd85db0, 0xffc818, 0x13, 0x3c1cdc0, 0x1, 0x1, 0x18b9c0, 0x10, 0x18bf94)
        /usr/local/go/src/reflect/value.go:308 +0x74
text/template.safeCall(0xd85db0, 0xffc818, 0x13, 0x3c1cdc0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/text/template/funcs.go:293 +0x90
text/template.(*state).evalCall(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0xd85db0, 0xffc818, 0x13, 0x1279b08, 0x3f39be0, 0xf7eeef, ...)
        /usr/local/go/src/text/template/exec.go:703 +0x508
text/template.(*state).evalFunction(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0x3f39bc0, 0x1279b08, 0x3f39be0, 0x39424c0, 0x1, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:564 +0xf4
text/template.(*state).evalCommand(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0x3f39be0, 0xdab050, 0x3378e48, 0x98, 0xdab050, 0x3378e48, ...)
        /usr/local/go/src/text/template/exec.go:461 +0x560
text/template.(*state).evalPipeline(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0x2ec61e0, 0x0, 0x0, 0x2d5ee40)
        /usr/local/go/src/text/template/exec.go:430 +0xd8
text/template.(*state).walk(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0x1279a68, 0x2d5ef80)
        /usr/local/go/src/text/template/exec.go:254 +0x3ec
text/template.(*state).walk(0x45e1a04, 0xe6c850, 0x2ded438, 0x194, 0x1279bd0, 0x2d5e7e0)
        /usr/local/go/src/text/template/exec.go:262 +0xec
text/template.(*state).walkRange.func1(0xdaa540, 0x495408c, 0x82, 0xe6c850, 0x2ded438, 0x194)
        /usr/local/go/src/text/template/exec.go:349 +0x108
text/template.(*state).walkRange(0xe60fa04, 0xf15160, 0x30eda40, 0x16, 0x2d66a00)
        /usr/local/go/src/text/template/exec.go:358 +0x420
text/template.(*state).walk(0xe60fa04, 0xf15160, 0x30eda40, 0x16, 0x1279c70, 0x2d66a00)
        /usr/local/go/src/text/template/exec.go:265 +0x3a0
text/template.(*state).walk(0x45e1a04, 0xf15160, 0x30eda40, 0x16, 0x1279bd0, 0x2ec34c0)
        /usr/local/go/src/text/template/exec.go:262 +0xec
text/template.(*state).walkTemplate(0xe60faec, 0xf15160, 0x30eda40, 0x16, 0x2d77360)
        /usr/local/go/src/text/template/exec.go:412 +0x184
text/template.(*state).walk(0xe60faec, 0xf15160, 0x30eda40, 0x16, 0x1279cc0, 0x2d77360)
        /usr/local/go/src/text/template/exec.go:267 +0x19c
text/template.(*state).walk(0x45e1aec, 0xf15160, 0x30eda40, 0x16, 0x1279bd0, 0x2d76ea0)
        /usr/local/go/src/text/template/exec.go:262 +0xec
text/template.(*Template).execute(0x2e29620, 0x1267b08, 0x6bd56c0, 0xf15160, 0x30eda40, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:217 +0x140
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:200
html/template.(*Template).Execute(0x2d77520, 0x1267b08, 0x6bd56c0, 0xf15160, 0x30eda40, 0x126ee01, 0x126ee40)
        /usr/local/go/src/html/template/template.go:122 +0x6c
github.com/gohugoio/hugo/tpl.(*TemplateAdapter).Execute(0x3c6cff0, 0x1267b08, 0x6bd56c0, 0xf15160, 0x30eda40, 0x0, 0x0)
        /root/project/hugo/tpl/template.go:163 +0x90
github.com/gohugoio/hugo/hugolib.(*Site).renderForLayouts(0x2b9e540, 0xf1c4fe, 0x4, 0xf1b3f6, 0x4, 0xf15160, 0x30eda40, 0x1267b08, 0x6bd56c0, 0x3bb2380, ...)
        /root/project/hugo/hugolib/site.go:1724 +0x70
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0x2b9e540, 0x2afc3c8, 0xe60fe8c, 0x14, 0x326ced0, 0x2c, 0x30eda40, 0x3bb2380, 0x10, 0x10, ...)
        /root/project/hugo/hugolib/site.go:1640 +0x110
github.com/gohugoio/hugo/hugolib.pageRenderer(0x3c6fe20, 0x2b9e540, 0x3234c40, 0x37a36c0, 0x3cea010)
        /root/project/hugo/hugolib/site_render.go:152 +0x428
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /root/project/hugo/hugolib/site_render.go:73 +0x104

goroutine 127 [chan receive]:
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build.func1(0x2bce480, 0x3461600, 0x2d9c200)
        /root/project/hugo/hugolib/hugo_sites_build.go:49 +0x68
created by github.com/gohugoio/hugo/hugolib.(*HugoSites).Build
        /root/project/hugo/hugolib/hugo_sites_build.go:46 +0x150

goroutine 135 [runnable]:
github.com/tdewolff/parse/v2.QuoteEntity(0x6a4e252, 0xa478f, 0x116abe, 0x3654000, 0x0)
        /go/pkg/mod/github.com/tdewolff/parse/v2@v2.3.5/common.go:193 +0x320
github.com/tdewolff/parse/v2/html.EscapeAttrVal(0x284f908, 0x2a918ed6, 0x1049e4, 0x87a72a, 0x69ee000, 0x1049e1, 0x176d10, 0x3654000, 0x2b90ba0, 0x0)
        /go/pkg/mod/github.com/tdewolff/parse/v2@v2.3.5/html/util.go:64 +0xe0
github.com/tdewolff/minify/v2/html.(*Minifier).Minify(0x2a8e030, 0x2be3d00, 0x1267b08, 0x6588e20, 0x1267af0, 0x473e240, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/tdewolff/minify/v2@v2.3.7/html/html.go:445 +0x11d8
github.com/tdewolff/minify/v2.MinifierFunc.Minify(...)
        /go/pkg/mod/github.com/tdewolff/minify/v2@v2.3.7/minify.go:29
github.com/gohugoio/hugo/minifiers.Client.Transformer.func1(0x126ee88, 0x2b8e110, 0x6588e20, 0xbe70ea)
        /root/project/hugo/minifiers/minifiers.go:53 +0x9c
github.com/gohugoio/hugo/transform.(*Chain).Apply(0x284fb10, 0x1267b08, 0x37730e0, 0x1267af0, 0x4e18060, 0x0, 0x0)
        /root/project/hugo/transform/chain.go:105 +0x1cc
github.com/gohugoio/hugo/publisher.DestinationPublisher.Publish(0x1281348, 0x2b3dd80, 0x35f9501, 0x2be3d00, 0x1267af0, 0x4e18060, 0xf1b3f6, 0x4, 0xf1c8d6, 0x4, ...)
        /root/project/hugo/publisher/publisher.go:100 +0x2a8
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0x2b9e540, 0x2afc3c8, 0x3d35e8c, 0x1b, 0x3c66100, 0x33, 0x36f57c0, 0x3bb2380, 0x10, 0x10, ...)
        /root/project/hugo/hugolib/site.go:1689 +0x294
github.com/gohugoio/hugo/hugolib.pageRenderer(0x3c6fe20, 0x2b9e540, 0x3234c40, 0x37a36c0, 0x3cea010)
        /root/project/hugo/hugolib/site_render.go:152 +0x428
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /root/project/hugo/hugolib/site_render.go:73 +0x104

goroutine 134 [runnable]:
github.com/tdewolff/parse/v2.QuoteEntity(0xe228363, 0xacd4e, 0x1b1b61, 0x13ce0000, 0x0)
        /go/pkg/mod/github.com/tdewolff/parse/v2@v2.3.5/common.go:193 +0x320
github.com/tdewolff/parse/v2/html.EscapeAttrVal(0xe60b908, 0x31f82891, 0xef0b5, 0xf7b56f, 0xe1e6000, 0xef0b1, 0x1f3ec4, 0x3ca0f40, 0x2b90ba0, 0x0)
        /go/pkg/mod/github.com/tdewolff/parse/v2@v2.3.5/html/util.go:110 +0x39c
github.com/tdewolff/minify/v2/html.(*Minifier).Minify(0x2a8e030, 0x2be3d00, 0x1267b08, 0x4146000, 0x1267af0, 0x41470c0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/tdewolff/minify/v2@v2.3.7/html/html.go:445 +0x11d8
github.com/tdewolff/minify/v2.MinifierFunc.Minify(...)
        /go/pkg/mod/github.com/tdewolff/minify/v2@v2.3.7/minify.go:29
github.com/gohugoio/hugo/minifiers.Client.Transformer.func1(0x126ee88, 0x3724000, 0x4146000, 0xd31082)
        /root/project/hugo/minifiers/minifiers.go:53 +0x9c
github.com/gohugoio/hugo/transform.(*Chain).Apply(0xe60bb10, 0x1267b08, 0x4146900, 0x1267af0, 0x3553e00, 0x0, 0x0)
        /root/project/hugo/transform/chain.go:105 +0x1cc
github.com/gohugoio/hugo/publisher.DestinationPublisher.Publish(0x1281348, 0x2b3dd80, 0x3f04601, 0x2be3d00, 0x1267af0, 0x3553e00, 0xf1b3f6, 0x4, 0xf1c8d6, 0x4, ...)
        /root/project/hugo/publisher/publisher.go:100 +0x2a8
github.com/gohugoio/hugo/hugolib.(*Site).renderAndWritePage(0x2b9e540, 0x2afc3c8, 0xe60be8c, 0x10, 0x369cf30, 0x28, 0x3798040, 0x8bc8f00, 0x8, 0x8, ...)
        /root/project/hugo/hugolib/site.go:1689 +0x294
github.com/gohugoio/hugo/hugolib.pageRenderer(0x3c6fe20, 0x2b9e540, 0x3234c40, 0x37a36c0, 0x3cea010)
        /root/project/hugo/hugolib/site_render.go:152 +0x428
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /root/project/hugo/hugolib/site_render.go:73 +0x104

goroutine 133 [chan receive]:
github.com/gohugoio/hugo/hugolib.(*Site).errorCollator(0x2b9e540, 0x37a36c0, 0x37a3700)
        /root/project/hugo/hugolib/site.go:1566 +0x5c
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /root/project/hugo/hugolib/site_render.go:67 +0x98

**Comment by gj52** [comment]
not gone with 0.56.1

If I `delete ./recources` the error comes back for some runs.
--> could this be a memory leak in image processing?
I only use .Fit   and  `.Content | base64Encode `
