### ISSUE TITLE
Building sites … panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tareefdev** [gohugoio/hugo#6340]
I have a site working perfectly on my machine, but I get the following error when trying to build it on another one:

```
Building sites … panic: runtime error: index out of range

goroutine 74 [running]:
github.com/chaseadamsio/goorgeous.findTags(0x1bd3bc2, 0xb5, 0x43e, 0x0, 0x20, 0x3, 0x0, 0x0)
        github.com/chaseadamsio/goorgeous/goorgeous.go:432 +0x230
github.com/chaseadamsio/goorgeous.(*parser).generateHeadline(0x1d90900, 0x1895800, 0x1bd3bc2, 0xb5, 0x43e)
        github.com/chaseadamsio/goorgeous/goorgeous.go:378 +0x150
github.com/chaseadamsio/goorgeous.OrgOptions(0x1db3000, 0x4102, 0x4800, 0xbadb08, 0x1bcbc30, 0x0, 0x0, 0x0)
        github.com/chaseadamsio/goorgeous/goorgeous.go:231 +0x1124
github.com/chaseadamsio/goorgeous.Org(0x1db3000, 0x4102, 0x4800, 0xbadb08, 0x1bcbc30, 0x20, 0x184fc78, 0x0)
        github.com/chaseadamsio/goorgeous/goorgeous.go:50 +0x3c
github.com/gohugoio/hugo/helpers.orgRender(0x1bcffc0, 0x1942120, 0x0, 0x0, 0x0, 0x0, 0x46, 0x0, 0x19716a0, 0x1971680, ...)
        github.com/gohugoio/hugo/helpers/content.go:736 +0x150
github.com/gohugoio/hugo/helpers.ContentSpec.RenderBytes(0x1942120, 0x0, 0x0, 0x0, 0x0, 0x46, 0x0, 0x19716a0, 0x1971680, 0xb9f300, ...)
        github.com/gohugoio/hugo/helpers/content.go:482 +0x178
github.com/gohugoio/hugo/hugolib.(*Page).renderContent(0x1a0eb00, 0x1dae800, 0x4102, 0x4102, 0x0, 0x0, 0x0)
        github.com/gohugoio/hugo/hugolib/page.go:829 +0x170
github.com/gohugoio/hugo/hugolib.(*contentHandlers).handlePageContent.func1(0x1d4da00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/gohugoio/hugo/hugolib/pagebundler_handlers.go:276 +0x80
github.com/gohugoio/hugo/hugolib.(*contentHandlers).processFirstMatch.func1(0x1d4da00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/gohugoio/hugo/hugolib/pagebundler_handlers.go:85 +0x68
github.com/gohugoio/hugo/hugolib.(*contentHandlers).parsePage.func1(0x1d4da00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/gohugoio/hugo/hugolib/pagebundler_handlers.go:264 +0x250
github.com/gohugoio/hugo/hugolib.(*contentHandlers).processFirstMatch.func1(0x1d4da00, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/gohugoio/hugo/hugolib/pagebundler_handlers.go:85 +0x68
github.com/gohugoio/hugo/hugolib.(*siteContentProcessor).readAndConvertContentFile(0x1bc56b0, 0x1d4d9e0, 0x2, 0x0)
        github.com/gohugoio/hugo/hugolib/pagebundler.go:203 +0x64
github.com/gohugoio/hugo/hugolib.(*siteContentProcessor).process.func2(0x4, 0xa180fc)
        github.com/gohugoio/hugo/hugolib/pagebundler.go:130 +0xe0
golang.org/x/sync/errgroup.(*Group).Go.func1(0x1c32840, 0x18a2000)
        golang.org/x/sync/errgroup/errgroup.go:58 +0x48
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync/errgroup/errgroup.go:55 +0x50
```

The first device where Hugo builds done without any problem:
```
Hugo Static Site Generator v0.58.1/extended linux/amd64 BuildDate: unknown
GOOS="linux"
GOARCH="amd64"
GOVERSION="go1.13"
```

The second one where the issue occurs:
```
Hugo Static Site Generator v0.54.0/extended linux/arm BuildDate: 2019-06-04T19:16:36Z
GOOS="linux"
GOARCH="arm"
GOVERSION="go1.11.6"
```

**Comment by bep** [comment]
We have changed the library used to parse Org files, which means that if you want this fixed on the "second device", you need to update Hugo.

**Comment by tareefdev** [comment]
That solved the issue, thanks.
