### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by essare** [gohugoio/hugo#6806]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.63.1 linux/amd64 BuildDate: 2020-01-24T01:20:28Z
</pre>

### Does this issue reproduce with the latest release?
Yes

installed hugo from snap
and when running `hugo server` in throws following stacktrace
-------------------------
$ uname -a
Linux essare 4.15.0-30deepin-generic #31 SMP Fri Nov 30 04:29:02 UTC 2018 x86_64 GNU/Linux

Thrown error:

``` 
$ hugo server
port 1313 already in use, attempting to use an available port
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x16cb907]

goroutine 1 [running]:
github.com/gohugoio/hugo/commands.(*serverCmd).server.func1.1()
	/build/hugo/parts/hugo/build/commands/server.go:193 +0x437
sync.(*Once).doSlow(0xc0005012d0, 0xc000751748)
	/snap/go/5185/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
	/snap/go/5185/src/sync/once.go:57
github.com/gohugoio/hugo/commands.(*serverCmd).server.func1(0xc000761110, 0x1bc0438, 0x13)
	/build/hugo/parts/hugo/build/commands/server.go:166 +0x8b4
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc000761110, 0xc000760101, 0x1f9d440, 0xc000566fb0)
	/build/hugo/parts/hugo/build/commands/commandeer.go:342 +0x923
github.com/gohugoio/hugo/commands.newCommandeer(0x101, 0xc0005775f0, 0x1f9ae60, 0xc00059b700, 0xc000360940, 0x0, 0x0, 0x0, 0x19dbf40, 0xc000772d00, ...)
	/build/hugo/parts/hugo/build/commands/commandeer.go:184 +0x241
github.com/gohugoio/hugo/commands.initializeConfig(0x101, 0xc0005775f0, 0x1f9ae60, 0xc00059b700, 0xc000360940, 0x0, 0x0, 0xc000310958)
	/build/hugo/parts/hugo/build/commands/hugo.go:123 +0x76
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc00059b700, 0xc000754780, 0x2cfb430, 0x0, 0x0, 0x0, 0x0)
	/build/hugo/parts/hugo/build/commands/server.go:238 +0x1c5
github.com/spf13/cobra.(*Command).execute(0xc000754780, 0x2cfb430, 0x0, 0x0, 0xc000754780, 0x2cfb430)
	/build/hugo/parts/hugo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0xc000764280, 0xc000566d60, 0xc000751ec0, 0x16a6872)
	/build/hugo/parts/hugo/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/gohugoio/hugo/commands.Execute(0xc0000c2010, 0x1, 0x1, 0x4074ff, 0xc0000a4058, 0x0, 0x0)
	/build/hugo/parts/hugo/build/commands/hugo.go:89 +0xb9
main.main()
	/build/hugo/parts/hugo/build/main.go:23 +0x6c
```

**Comment by windtail** [comment]
This is something related to snap, install with [binary](https://github.com/gohugoio/hugo/releases) without this issue for version `hugo v0.83.1-5AFE0A57+extended linux/amd64 BuildDate=2021-05-02T14:38:05Z VendorInfo=gohugoio`
