### ISSUE TITLE
 panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pgporada** [gohugoio/hugo#6857]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.65.0-DEV linux/amd64 BuildDate: unknown

Built from 6a74cbe9167a431256b22dd1fb53eaeb9f1808ea
</pre>

### Does this issue reproduce with the latest release?
Yes

Hi,

I received the following panic while figuring out how to use `.Inner` over at https://github.com/letsencrypt/website/pull/893
```
$ hugo server -F
Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xf5a608]

goroutine 60 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000b3b0c0, 0x4, 0x0, 0xc0007e4940, 0x0, 0x0, 0x17db460)
        /home/user/hugo/hugolib/shortcode.go:505 +0x898
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc000a09da0, 0xc0000fc9a0, 0xc001401400, 0x0, 0xc000b81b38)
        /home/user/hugo/hugolib/page.go:738 +0xb16
github.com/gohugoio/hugo/hugolib.newPageWithContent.func1(0xc0000fc9a0, 0x42f92a, 0xc000b81b90)
        /home/user/hugo/hugolib/page__new.go:233 +0x4b
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMeta.func1()
        /home/user/hugo/hugolib/pages_map.go:77 +0x50
sync.(*Once).doSlow(0xc000d7cf20, 0xc000b81c08)
        /usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMeta(0xc00077ea20, 0xc000a09da0, 0xc0000fc9a0, 0x1b69db3, 0x4)
        /home/user/hugo/hugolib/pages_map.go:75 +0xa1
github.com/gohugoio/hugo/hugolib.(*pagesMap).initPageMetaFor(0xc00077ea20, 0xc0008825da, 0x5, 0xc0000fc9a0, 0x0, 0x203fea0)
        /home/user/hugo/hugolib/pages_map.go:95 +0x429
github.com/gohugoio/hugo/hugolib.(*pagesMap).assemblePageMeta.func1(0xc0008825da, 0x5, 0x1950f20, 0xc0000fc9a0, 0xc000a80030)
        /home/user/hugo/hugolib/pages_map.go:199 +0x66
github.com/armon/go-radix.recursiveWalk(0xc0016f8630, 0xc000b81ea0, 0x1b66616)
        /home/user/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc0016f87e0, 0xc000b81ea0, 0x1950f20)
        /home/user/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0016f85d0, 0xc000b81ea0, 0xc000a6c336)
        /home/user/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0016f8570, 0xc000b81ea0, 0x0)
        /home/user/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
        /home/user/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pagesMap).assemblePageMeta(0xc00077ea20, 0xc000035c00, 0x0)
        /home/user/hugo/hugolib/pages_map.go:196 +0x6c
github.com/gohugoio/hugo/hugolib.(*HugoSites).assemble.func1(0x0, 0x0)
        /home/user/hugo/hugolib/hugo_sites_build.go:266 +0xff
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc001024900, 0xc001024930)
        /home/user/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/user/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

Reproduction case:
`layouts/shortcodes/test.html` is an empty file
`content/en/docs/test.md`
```
---
title: Test
slug: test
top_graphic: 4
lastmod: 2020-02-05
---

{{< test >}}
{{< /test >}}
```

If I use the following `content/en/docs/test.md` instead, I do not get the SIGSEGV.
```
---
title: Test
slug: test
top_graphic: 4
lastmod: 2020-02-05
---

{{< test >}}
```

**Comment by nlune** [comment]
I have the exact same issue. Trying out how to create a shortcode by following the video tutorial exactly, I just made a html for the shortcode and a paragraph with .Inner in the it. But for some reason when I try to run the server I get:

``` 
Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xfc5022]

goroutine 122 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000a45100, 0x1, 0x0, 0xc0000790b0, 0xc0012fefe8, 0x6, 0x1a6c3c0)
	/build/hugo/parts/hugo/build/hugolib/shortcode.go:505 +0x882
...
 ```

**Comment by eweiss99** [comment]
On Mac (Monterey) running `hugo server -F` I get the same error. I downloaded and installed hugo earlier today.

**Comment by jmooring** [comment]
@eweiss99 Commenting on closed issues is not productive. Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting. We prefer to use GitHub for verified bugs and vetted enhancements. Thanks.
