### ISSUE TITLE
panic: nil dereference error when shortcode blocks are used

### ISSUE THREAD

**Issue by ahmetb** [gohugoio/hugo#6984]
Possibly identical to #6866 and #6857.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
v0.65.3/extended
</pre>

### Does this issue reproduce with the latest release?

Yes, this is the latest release available.

### What happened

I just added this `shortcodes/buttongroup.html`:

```
<div class="btn-group" role="group">
    {{.}}
</div>
```

then I added this to my content markdown file:

```
{{% buttongroup %}}
foo
{{% /buttongroup %}}
```

then my `hugo serve` crashed, and subsequent `hugo serve` commands now fail with:

```
Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4b682e8]

goroutine 117 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc000984080, 0x1, 0x0, 0xc0009491b0, 0x0, 0x0, 0x5566480)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/shortcode.go:505 +0x898
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc00096adb0, 0xc0008acbd0, 0xc00096ea00, 0xc00095d540, 0x5d41080)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/page.go:771 +0xb9e
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc00072a6d0, 0xc0008cff20, 0xc0008acbd0, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:164 +0x637
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc000916090, 0x28, 0x563fb40, 0xc0008cff20, 0xc0008dfd00)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:358 +0x16d
github.com/armon/go-radix.recursiveWalk(0xc0008cff80, 0xc0008dfdf0, 0x4818400)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc00094a000, 0xc0008dfdf0, 0x4818400)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0008cff50, 0xc0008dfdf0, 0x4b42200)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc00091e2d0, 0xc0008dfdf0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc0007fbd70, 0xc0008dfdf0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc00072a6d0, 0x0, 0x0)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:331 +0xec
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc00072a6d0, 0x0, 0x0)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:709 +0x68
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/hugolib/content_map_page.go:776 +0x2e
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc000645768, 0x0)
	/private/tmp/hugo-20200223-12002-c2aj98/hugo-0.65.3/src/github.com/gohugoio/hugo/common/para/para.go:52 +0x2f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00094a060, 0xc0008fb2e0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

Removing the shortcode usage from markdown file mitigates the problem.

**Comment by glani** [comment]
0.67.0 the same behavior. any updates when it will be fixed ?

**Comment by ryanfaerman** [comment]
I had a similar experience. What I found is that if you're using a shortcode that contains an `.Inner` and not using it, you get a panic.

So if your shortcode is something like `{{% myshortcode % }} foo {{% /myshortcode %}}` but your layout shortcode is:

```html
<strong>{{ . }}</strong>
```

You'll get a panic.

If, instead, you change your layout to:

```html
<strong>{{ .Inner }}</strong>
```

The problem goes away. This probably shouldn't panic and should fail gracefully, but that's how you work around the issue.
