### ISSUE TITLE
Hugo 0.68.3 crashed with i18n enabled

### ISSUE THREAD

**Issue by LunaticMuch** [gohugoio/hugo#7104]
After update to 0.68, I've found that I cannot start my site anymore. When I run `hugo server`I get the following stack trace:

```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/nicksnyder/go-i18n/i18n/bundle.deleteLeadingComments(0xc0006b74ba, 0x5, 0xc00066d25a, 0x2, 0x2, 0xc0009beaf0, 0x49a97ef806db919c, 0x8)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/nicksnyder/go-i18n@v1.10.0/i18n/bundle/bundle.go:137 +0x15a
github.com/nicksnyder/go-i18n/i18n/bundle.isStandardFormat(0xc0006b74ba, 0x5, 0xc00066d25a, 0x2, 0x2, 0xc0006b74b8)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/nicksnyder/go-i18n@v1.10.0/i18n/bundle/bundle.go:123 +0x57
github.com/nicksnyder/go-i18n/i18n/bundle.parseTranslations(0xc0006b74b8, 0x7, 0xc00066d25a, 0x2, 0x2, 0x6a10a00, 0x58258c0, 0xc000673290, 0xc0009bedc0, 0x48cab77)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/nicksnyder/go-i18n@v1.10.0/i18n/bundle/bundle.go:107 +0xc2
github.com/nicksnyder/go-i18n/i18n/bundle.(*Bundle).ParseTranslationFileBytes(0xc000672f60, 0xc0006b74b8, 0x7, 0xc00066d25a, 0x2, 0x2, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/nicksnyder/go-i18n@v1.10.0/i18n/bundle/bundle.go:75 +0xdb
github.com/gohugoio/hugo/langs/i18n.addTranslationFile(0xc000672f60, 0x5d273a0, 0xc0006144b0, 0x0, 0x0)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/langs/i18n/translationProvider.go:98 +0x13f
github.com/gohugoio/hugo/langs/i18n.(*TranslationProvider).Update(0xc000593580, 0xc000948fc0, 0x0, 0x0)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/langs/i18n/translationProvider.go:79 +0x2d3
github.com/gohugoio/hugo/deps.(*Deps).LoadResources(0xc000948fc0, 0x0, 0x0)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/deps/deps.go:178 +0x43
github.com/gohugoio/hugo/hugolib.applyDeps(0xc0008fdcb0, 0xc0009c2300, 0xc000315680, 0x0, 0x0, 0x5d21d60, 0xc00023e900, 0xc00017d000, 0x17, 0x27, ...)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:466 +0x395
github.com/gohugoio/hugo/hugolib.newHugoSites(0xc0008fdcb0, 0xc0009c2300, 0x0, 0x0, 0x0, 0x5d21d60, 0xc00023e900, 0x0, 0x0, 0x0, ...)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:355 +0x5c6
github.com/gohugoio/hugo/hugolib.NewHugoSites(0xc0008fdcb0, 0xc0009c2300, 0x0, 0x0, 0x0, 0x5d21d60, 0xc00023e900, 0x0, 0x0, 0x0, ...)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:488 +0x113
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/commandeer.go:399 +0x264
sync.(*Once).doSlow(0xc0006720d0, 0xc0009bf988)
	/usr/local/Cellar/go/1.14/libexec/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
	/usr/local/Cellar/go/1.14/libexec/src/sync/once.go:57
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0006760d0, 0xc000670101, 0x5cec660, 0xc000670070)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/commandeer.go:358 +0x865
github.com/gohugoio/hugo/commands.newCommandeer(0x101, 0xc00075a680, 0x5ce9e80, 0xc000389680, 0xc000592120, 0x0, 0x0, 0x0, 0x56ff3a0, 0xc00090d200, ...)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/commandeer.go:185 +0x241
github.com/gohugoio/hugo/commands.initializeConfig(0x101, 0xc00075a680, 0x5ce9e80, 0xc000389680, 0xc000592120, 0x0, 0x0, 0xc0002be000)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/hugo.go:123 +0x76
github.com/gohugoio/hugo/commands.(*serverCmd).server(0xc000389680, 0xc00089bb80, 0x6a74e20, 0x0, 0x0, 0x0, 0x0)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/server.go:238 +0x1d5
github.com/spf13/cobra.(*Command).execute(0xc00089bb80, 0x6a74e20, 0x0, 0x0, 0xc00089bb80, 0x6a74e20)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000901b80, 0xc0008fa350, 0x8, 0xc0004b6500)
	/Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/gohugoio/hugo/commands.Execute(0xc00000e070, 0x1, 0x1, 0x4007f6f, 0xc000100058, 0x0, 0x0)
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/commands/hugo.go:89 +0xb9
main.main()
	/private/tmp/hugo-20200324-99626-1rv8z5t/hugo-0.68.3/src/github.com/gohugoio/hugo/main.go:23 +0x6c
```

My version, updated on Mac with brew, is `Hugo Static Site Generator v0.68.3/extended darwin/amd64 BuildDate: unknown`

Apparently, if I remove the directory `i18n` from my template, hugo starts. The presence of the directory, even if empty, causes the issue. 
Other sites I have locally continue to work.

Thanks
Ste

**Comment by bep** [comment]
This is odd as we haven't updated that failing library in years What version did you update from?

**Comment by LunaticMuch** [comment]
It needs more investigation. I've workarounded using` .toml `for i18n translation as the routine `deleteLeadingComments` is executed specifically agaisnst yaml.
It might be the case of a bad character which seems not visible or some weird letter coming up from German translation but not sure, cause I made a case without de.yaml and it was failing anyway.

**Comment by moorereason** [comment]
@LunaticMuch, can you try the latest Hugo?  The i18n landscape has changes since your last comment.
