### ISSUE TITLE
Crash when paired shortcode doesn't use .Inner

### ISSUE THREAD

**Issue by mooskagh** [gohugoio/hugo#7121]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?
Yes.

Steps to reproduce:
1. Create a shortcode without using .Inner, for example with the following content:
```
test
```
and save it to `layouts/shortcodes/myshortcode.html`

2. In the content document (e.g. in `content/test/mydocument.md`), use the shortcode in the following way:
```
{{< myshortcode >}}
{{< /myshortcode >}}
```

3. Run the hugo:
```
$ hugo -DF server
```

4. Note it crashes:

```
$ hugo -DF server
Building sites … panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x56197d2c0aa4]

goroutine 82 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc0007ff800, 0x1, 0x0, 0xc00058fe60, 0x0, 0x0, 0x56197e10a2a0)
	/build/hugo/src/hugo-0.68.3/hugolib/shortcode.go:505 +0x884
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc0009bb710, 0xc000908940, 0xc0009f6000, 0xc0009c3380, 0x56197e4c89a0)
	/build/hugo/src/hugo-0.68.3/hugolib/page.go:783 +0xb82
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000580660, 0xc0000e8e70, 0xc000908940, 0x0, 0x0, 0x0, 0x0)
	/build/hugo/src/hugo-0.68.3/hugolib/content_map_page.go:164 +0x627
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc00090a6c0, 0x14, 0x56197e1d6b80, 0xc0000e8e70, 0xc00092bc00)
	/build/hugo/src/hugo-0.68.3/hugolib/content_map_page.go:358 +0x152
github.com/armon/go-radix.recursiveWalk(0xc0000e8ea0, 0xc00092be10, 0x56197e1d6b00)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf2
github.com/armon/go-radix.recursiveWalk(0xc0000e8e10, 0xc00092be10, 0x56197cf75c00)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x80
github.com/armon/go-radix.recursiveWalk(0xc0007f60f0, 0xc00092be10, 0x56197d29acc4)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x80
github.com/armon/go-radix.recursiveWalk(0xc0005da3c0, 0xc00092be10, 0x0)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x80
github.com/armon/go-radix.recursiveWalk(0xc0007a7320, 0xc00092be10, 0x0)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x80
github.com/armon/go-radix.(*Tree).Walk(...)
	/build/go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000580660, 0x0, 0x0)
	/build/hugo/src/hugo-0.68.3/hugolib/content_map_page.go:331 +0xee
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000580660, 0x0, 0x0)
	/build/hugo/src/hugo-0.68.3/hugolib/content_map_page.go:721 +0x6a
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0x0, 0x0)
	/build/hugo/src/hugo-0.68.3/hugolib/content_map_page.go:788 +0x30
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0x0, 0x0)
	/build/hugo/src/hugo-0.68.3/common/para/para.go:52 +0x31
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008b63c0, 0xc000988200)
	/build/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x5b
created by golang.org/x/sync/errgroup.(*Group).Go
	/build/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x68
```

**Comment by bric3** [comment]
It's probably irrelevant this fails on darwoin as well.

**Comment by jmert** [comment]
I was just bitten by this bug, and it took a while to figure out the source of the problem. As far as I can tell, the documentation doesn't say a reference to `.Inner` is required, so I expected a null-sink shortcode (`null.html`) such as an empty file or a minimal
```
{{- "" -}}
```
to work. Instead, I found I have to unconditionally not use the contents with
```
{{- if false }}{{ .Inner }}{{ end -}}
```
to avoid the crash and still eat the shortcode contents.
