### ISSUE TITLE
Invalid JSON results in SIGSEGV when building in production

### ISSUE THREAD

**Issue by virgofx** [gohugoio/hugo#7210]
```
hugo --verbose --minify --cleanDestinationDir --environment production
```

Stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
website    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17c8f3e]
website    |
website    | goroutine 111 [running]:
website    | github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc0007b3d40, 0xc001863e60, 0xc001e08ef0, 0xc00041e540, 0x6, 0x8, 0xc001ccc660)
website    |    /root/project/hugo/commands/hugo.go:1045 +0x153e
website    | github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc001863e60, 0xc0007b3d40, 0xc001e08ef0, 0xc001ccc660)     
website    |    /root/project/hugo/commands/hugo.go:841 +0x1d8
website    | created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
website    |    /root/project/hugo/commands/hugo.go:837 +0x28d
website    | error Command failed with exit code 2.
```

Stack Trace 2 (Testing similar live reloads in development)
```
website    | panic: runtime error: index out of range [4] with length 4
website    |
website    | goroutine 112 [running]:
website    | github.com/gohugoio/hugo/hugolib.(*pageState).shiftToOutputFormat(0xc003068a80, 0x1, 0x4, 0xc004280001, 0xc000cc92f0)        
website    |    /root/project/hugo/hugolib/page.go:916 +0x357
website    | github.com/gohugoio/hugo/hugolib.(*pageState).initOutputFormat(...)
website    |    /root/project/hugo/hugolib/page.go:474
website    | github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender.func1(0xc003068a80, 0xc000705b00)
website    |    /root/project/hugo/hugolib/hugo_sites.go:754 +0x49
website    | github.com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage.func1(0xc0040f93c0, 0x11, 0xc0041ba4b0, 0xc0042850e0)        
website    |    /root/project/hugo/hugolib/content_map_page.go:696 +0x37
website    | github.com/gohugoio/hugo/hugolib.contentTrees.Walk.func1(0xc0040f93c0, 0x11, 0x1ae0a00, 0xc0041ba4b0, 0xc0042850e0)
website    |    /root/project/hugo/hugolib/content_map.go:851 +0x54
website    | github.com/armon/go-radix.recursiveWalk(0xc0041ba4e0, 0xc000cc9488, 0xc00004e800)
website    |    /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
website    | github.com/armon/go-radix.recursiveWalk(0xc0041badb0, 0xc000cc9488, 0xc001e43ec0)
website    |    /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
website    | github.com/armon/go-radix.recursiveWalk(0xc0041ba5a0, 0xc000cc9488, 0x203000)
website    |    /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
website    | github.com/armon/go-radix.recursiveWalk(0xc0040612f0, 0xc000cc9488, 0xc8)
website    |    /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
website    | github.com/armon/go-radix.(*Tree).Walk(...)
website    |    /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
website    | github.com/gohugoio/hugo/hugolib.contentTrees.Walk(0xc00407a3c0, 0x4, 0x4, 0xc000cc94c8)
website    |    /root/project/hugo/hugolib/content_map.go:849 +0x67
website    | github.com/gohugoio/hugo/hugolib.(*pageMap).withEveryBundlePage(0xc00405dab0, 0xc000cc9508)
website    |    /root/project/hugo/hugolib/content_map_page.go:694 +0x6d
website    | github.com/gohugoio/hugo/hugolib.(*Site).preparePagesForRender(0xc000705b00, 0xc003579e01, 0x4, 0x0, 0x0)
website    |    /root/project/hugo/hugolib/hugo_sites.go:753 +0x84
website    | github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc003fc2c80, 0xc002e0b340, 0x30fa978, 0x1)
website    |    /root/project/hugo/hugolib/hugo_sites_build.go:314 +0x1cc
website    | github.com/gohugoio/hugo/hugolib.(*HugoSites).Build.func4()
website    |    /root/project/hugo/hugolib/hugo_sites_build.go:149 +0x3c
website    | runtime/trace.WithRegion(0x2339360, 0xc002e55500, 0x1d96ee2, 0x6, 0xc000cc9928)
website    |    /usr/local/go/src/runtime/trace/annotation.go:137 +0xfe
website    | github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc003fc2c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc002e554d0, 0x0, 0xc002e55470, ...)
website    |    /root/project/hugo/hugolib/hugo_sites_build.go:151 +0x7b5
website    | github.com/gohugoio/hugo/commands.(*commandeer).rebuildSites(0xc0007a96c0, 0xc002e55470, 0x2, 0x2, 0x0, 0x0)
website    |    /root/project/hugo/commands/hugo.go:734 +0x407
website    | github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc0007a96c0, 0xc001b84a20, 0xc001b99840, 0xc00319ad50, 0x2, 0x2, 0xc001a5fb60)
website    |    /root/project/hugo/commands/hugo.go:1099 +0x764
website    | github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc001b84a20, 0xc0007a96c0, 0xc001b99840, 0xc001a5fb60)     
website    |    /root/project/hugo/commands/hugo.go:841 +0x1d8
website    | created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
website    |    /root/project/hugo/commands/hugo.go:837 +0x28d
```

### How to Reproduce
Add JSON output with invalid JSON (There may be 2 issues - 1 issue is with minification)

It appears it renders invalid JSON fine in normal mode; however, I'm guessing it's breaking on uglifier. It would be nice to just handle the error gracefully without segfaulting.

1. Add a `./layouts/_default/{{kind}}.json` and then specify to use the html (assuming this is NOT JSON)
   ```
   {{ .Content }}
   ```
2. Update the `[outputs]` section in `config.toml` to include the `JSON` in the corresponding kind from previous step.

3. Run production build

Ideally, I'd like to set my `./layouts/_default/{{kind}}.json` to be **empty**.  This is valid as I only want certain `{{kind}}` sections to be rendered with JSON and not for everything. E.g. Say I want to render `/layouts/blog/section.json`  ... but not for other top level sections. Again, works fine in normal mode, but breaks production. 

Work-around. Define an empty/valid JSON in top level `_default/{{kind}}.json` `{}`

### Extra Details
Hugo Version: `0.69.2`
OS: `Linux / Debian GNU/Linux 9 (stretch)`

PS: Thank you maintainers for this wonderful project.

**Comment by virgofx** [comment]
Maybe related to: #6472 

Any chance this could get added to next release milestone @bep?

**Comment by virgofx** [comment]
Further analysis regarding the issue above ... it does appear to be triggered because of the translation of certain characters into JSON

**index.md** 
```
```bash
echo "hugo is awesome"
`` `  
# Note adding a space in prevoius line for it to showup in git markdown (not really there)
```

Resulting: **index.json** (Unminified)
```
{"html":"echo \u0026#34;hugo is awesome\u0026#34;"}
```

And then production breaks. 
Changing the markdown to remove the `bash` suffix:
```
echo "hugo is awesome"
`` `  
# Note adding a space in prevoius line for it to showup in git markdown (not really there)
```

Resulting: **index.json** (Unminified)
```
{"html":"echo \u0026quot;hugo is awesome\u0026quot;"}
```

And production build works.  

Hopefully that extra tidbit of information helps.

**Comment by bep** [comment]
I understand the "what" but not the "how" of this issue.

Hugo does not care about "valid JSON" or not, so that can not be it ...

**Comment by virgofx** [comment]
I believe the issue is during the minification algorithm ... something must happen where it traverses over JSON and causes some segfault somewhere. Taking out the above characters fixes the issue, but the stack trace hopefully provides enough info to maybe catch this ... it may be one of the external procesess?

**Comment by bep** [comment]
The SEGFAULT is a "index out of bounds" -- if you have a repo with this error then I can look at it.

**Comment by virgofx** [comment]
I'll setup a repo that reproduces the error. Thanks.

**Comment by danisztls** [comment]
I'm having a similar problem with invalid JSON.

**top excerpt from my rendered index JSON**
```json
const pages =
[{"description":"...
```

As you can see my JSON is in reality a Javascript file and unless I disable JSON minification it make Hugo crash when run with `--minify`.

**error message**
`
Error: Error building site: failed to render pages: JSON parse error: unexpected character 'c' on line 1 and column 1
    1: const pages
        ^
`
