### ISSUE TITLE
Hugo dumps when shortcode only closed but not opened

### ISSUE THREAD

**Issue by SirUli** [gohugoio/hugo#7322]
Hi,

currently running 0.71.1 but it also fails with 0.69 and all versions in between. In a Text i forgot to remove the closing part of a custom shortcode ( `{{% /notice %}}` ) which gave me the following dump when running `hugo server`:

```
goroutine 51 [running]:
github.com/gohugoio/hugo/hugolib.(*shortcodeHandler).extractShortcode(0xc002a3b600, 0x1, 0x0, 0xc002aafe40, 0x0, 0x0, 0x1bfe120)
        /root/project/hugo/hugolib/shortcode.go:505 +0x889
github.com/gohugoio/hugo/hugolib.(*pageState).mapContent(0xc002b58de0, 0xc000a63b60, 0xc002b49400, 0xc002b41fe0, 0x2414440)
        /root/project/hugo/hugolib/page.go:792 +0xb87
github.com/gohugoio/hugo/hugolib.(*pageMap).newPageFromContentNode(0xc000689ca0, 0xc000479890, 0xc000a63b60, 0x0, 0x0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:164 +0x62c
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages.func1(0xc000a44500, 0x35, 0x1bcf120, 0xc000479890, 0xc0008dfc00)
        /root/project/hugo/hugolib/content_map_page.go:363 +0x157
github.com/armon/go-radix.recursiveWalk(0xc0004798f0, 0xc0008dfe00, 0x1bcf100)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf7
github.com/armon/go-radix.recursiveWalk(0xc0007beff0, 0xc0008dfe00, 0x1bcf100)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github.com/armon/go-radix.recursiveWalk(0xc000a82330, 0xc0008dfe00, 0xfcde00)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github.com/armon/go-radix.recursiveWalk(0xc000a82240, 0xc0008dfe00, 0x0)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github.com/armon/go-radix.recursiveWalk(0xc00067f4d0, 0xc0008dfe00, 0x0)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x85
github.com/armon/go-radix.(*Tree).Walk(...)
        /go/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.(*pageMap).assemblePages(0xc000689ca0, 0x0, 0x0)
        /root/project/hugo/hugolib/content_map_page.go:336 +0xf3
github.com/gohugoio/hugo/hugolib.(*pageMaps).AssemblePages.func1(0xc000689ca0, 0xc000a5fa50, 0xc0006a3f00)
        /root/project/hugo/hugolib/content_map_page.go:717 +0x6f
github.com/gohugoio/hugo/hugolib.(*pageMaps).withMaps.func1(0xc000a5fa50, 0xc0006a3f68)
        /root/project/hugo/hugolib/content_map_page.go:785 +0x35
github.com/gohugoio/hugo/common/para.(*errGroupRunner).Run.func1(0xc000a5fa48, 0x0)
        /root/project/hugo/common/para/para.go:52 +0x36
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000b42180, 0xc00041b880)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x60
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x6d
```

Unfortunately the dump doesn't describe what the issue is and this it took me a while to identify 1) what is going on and 2) which file it is.

Maybe there is a possibility to have a more descriptive error rather than this dump?

Thanks in advance!

Best Regards, Uli

**Comment by SirUli** [comment]
Apparently this also happens the other way round: https://github.com/gohugoio/hugo/issues/7106

**Comment by Aescetic** [comment]
It's really more extreme than this. Something about commit `da814556567eab9ba0ac5fef5314c3ad5ee50ccd` breaks all betwixt-shortcode functionality.

**Comment by Aescetic** [comment]
Upon closer inspection, this is inaccurate. Rather, the failure is related to error handling in the `currItem.IsShortcodeClose()` case in `hugolib/shortcode.go`, line `503`: disable the error handling and the shortcode works as expected.

I will elaborate later.

**Comment by jmooring** [comment]
Tested again with 0.73. This:

```
foo

{{< /bar >}}

baz
```

produces this error message:

> got closing shortcode, but none is open

but it does not crash. I thin this issue can be closed.
