### ISSUE TITLE
server crash on new file detected

### ISSUE THREAD

**Issue by gwatts** [gohugoio/hugo#7538]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
Hugo Static Site Generator v0.74.3/extended darwin/amd64 BuildDate: unknown
</pre>

### Does this issue reproduce with the latest release?

Yes; 0.74.3 is the current latest release

### Summary

While hugo was running as `hugo serve --debug`, i created a new partial file in vim.  Hugo picked up the new file and crashed with the following backtrace:

```
Change detected, rebuilding site.
2020-08-07 16:19:27.658 -0500
DEBUG 2020/08/07 16:19:27 Rebuild for events ["\"/Users/gareth/projects/the-guide/layouts/partials/navbar.html\": CREATE"]
Template changed "/Users/gareth/projects/the-guide/layouts/partials/navbar.html": CREATE
Total in 135 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4cc1a26]

goroutine 228 [running]:
github.com/gohugoio/hugo/hugolib.(*BuildCfg).shouldRender(0xc000ec4000, 0x0, 0x4007400)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites.go:675 +0x26
github.com/gohugoio/hugo/hugolib.(*Site).renderPages.func1(0xc00163e280, 0x16, 0xc000dff350, 0xc001696c00)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/site_render.go:80 +0x4d
github.com/gohugoio/hugo/hugolib.contentTrees.Walk.func1(0xc00163e280, 0x16, 0x5781420, 0xc000dff350, 0xc000c5f400)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/content_map.go:870 +0x54
github.com/armon/go-radix.recursiveWalk(0xc000dff500, 0xc0008bb430, 0x5781400)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:519 +0xf0
github.com/armon/go-radix.recursiveWalk(0xc000dff4d0, 0xc0008bb430, 0x400eb00)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000c48f30, 0xc0008bb430, 0x5a46a00)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000c48ea0, 0xc0008bb430, 0x0)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.recursiveWalk(0xc000c1ebd0, 0xc0008bb430, 0xc0008bb460)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:525 +0x7e
github.com/armon/go-radix.(*Tree).Walk(...)
        /Users/brew/Library/Caches/Homebrew/go_cache/pkg/mod/github.com/armon/go-radix@v1.0.0/radix.go:447
github.com/gohugoio/hugo/hugolib.contentTrees.Walk(0xc000c19fe0, 0x3, 0x3, 0xc0008bb4c8)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/content_map.go:868 +0x67
github.com/gohugoio/hugo/hugolib.(*Site).renderPages(0xc0004f8900, 0xc0015b2100, 0x0, 0xc0008bb400)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/site_render.go:79 +0x1f8
github.com/gohugoio/hugo/hugolib.(*Site).render(0xc0004f8900, 0xc0015b2100, 0x0, 0x0)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/site.go:1203 +0x54
github.com/gohugoio/hugo/hugolib.(*HugoSites).render(0xc00090e840, 0xc000ec4000, 0x6e72820, 0x1)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:325 +0x40c
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build.func4()
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:149 +0x3c
runtime/trace.WithRegion(0x6029fa0, 0xc0011c8120, 0x5a593cd, 0x6, 0xc0008bb918)
        /usr/local/Cellar/go/1.14.5/libexec/src/runtime/trace/annotation.go:137 +0xfe
github.com/gohugoio/hugo/hugolib.(*HugoSites).Build(0xc00090e840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x100, 0xc0011c80f0, 0x0, 0xc001888140, ...)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/hugolib/hugo_sites_build.go:151 +0x7b5
github.com/gohugoio/hugo/commands.(*commandeer).rebuildSites(0xc000b12ea0, 0xc001888140, 0x1, 0x1, 0x0, 0x0)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/commands/hugo.go:774 +0x407
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc000b12ea0, 0xc0029920c0, 0xc001b0e5e8, 0xc001a22000, 0x1, 0x1, 0xc0008d9710)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/commands/hugo.go:1139 +0x764
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc0029920c0, 0xc000b12ea0, 0xc001b0e5e8, 0xc0008d9710)
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/commands/hugo.go:881 +0x1d8
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /private/tmp/hugo-20200723-37172-j46hmm/hugo-0.74.3/src/github.com/gohugoio/hugo/commands/hugo.go:877 +0x293
```

**Comment by ptgott** [comment]
I have not been able to reproduce this with the information given. I know it's been a long time, @gwatts, but do you happen to know the partial you created and the layout template it was included in? Otherwise, can we close this issue? Thanks!

**Comment by gwatts** [comment]
@ptgott  tried to reproduce it again just now using the same partial, etc but so far it hasn't recurred.    I haven't seen any similar crash in the past year either, so I think it's safe to close this - thanks for following up!
