### ISSUE TITLE
Add compatibility for Yarn 2.x Berry

### ISSUE THREAD

**Issue by wgroeneveld** [gohugoio/hugo#8301]
Hi there,

WIthout resorting to the `node-modules` yarn berry plugin (see https://yarnpkg.com/features/pnp ), Hugo pipes look for a `node-modules` path in which dependencies are typically listed. However, Yarn 2 works slightly differently. When using yarn in conjunction with hugo extended/pipes, the following happens:

```
Start building sites …
Built in 366 ms
Error: Error building site: BABEL: failed to transform "js/brainbaking.js" (application/javascript): Error: Cannot find module '@babel/preset-env'
Require stack:
- /Users/wgroeneveld/development/brainbaking/babel.config.js
- /opt/homebrew/lib/node_modules/@babel/core/lib/config/files/module-types.js
- /opt/homebrew/lib/node_modules/@babel/core/lib/config/files/configuration.js
- /opt/homebrew/lib/node_modules/@babel/core/lib/config/files/index.js
- /opt/homebrew/lib/node_modules/@babel/core/lib/index.js
- /opt/homebrew/lib/node_modules/@babel/cli/lib/babel/options.js
- /opt/homebrew/lib/node_modules/@babel/cli/lib/babel/index.js
- /opt/homebrew/lib/node_modules/@babel/cli/bin/babel.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at module.exports (/Users/wgroeneveld/development/brainbaking/babel.config.js:5:4)
    at readConfigJS (/opt/homebrew/lib/node_modules/@babel/core/lib/config/files/configuration.js:212:15)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/opt/homebrew/lib/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at step (/opt/homebrew/lib/node_modules/@babel/core/node_modules/gensync/index.js:261:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/wgroeneveld/development/brainbaking/babel.config.js',
    '/opt/homebrew/lib/node_modules/@babel/core/lib/config/files/module-types.js',
    '/opt/homebrew/lib/node_modules/@babel/core/lib/config/files/configuration.js',
    '/opt/homebrew/lib/node_modules/@babel/core/lib/config/files/index.js',
    '/opt/homebrew/lib/node_modules/@babel/core/lib/index.js',
    '/opt/homebrew/lib/node_modules/@babel/cli/lib/babel/options.js',
    '/opt/homebrew/lib/node_modules/@babel/cli/lib/babel/index.js',
    '/opt/homebrew/lib/node_modules/@babel/cli/bin/babel.js'
  ]
}
: exit status 1
```

This is because a `yarn install` command does **NOT** create `node-modules` but caches stuff locally in `.yarn/cache`. See above link. This can currently be "fixed" by letting Yarn produce a `node-modules` dir anyway, but it kind of defeats the purpose of using Yarn Berry. 

It would be cool if both tools understood each other in such a way that Hugo can leverage Yarn's caching abilities.

**Comment by wgroeneveld** [comment]
As a heads up for everyone, I also added hugo to the list at https://github.com/yarnpkg/berry/pull/2563

**Comment by bep** [comment]
So, Hugo vs JavaScript vs node_modules isn't _one_ thing. I see this is relates to Babel's config loading. I assume you would get the same troubles with PostCSS, maybe.

**Comment by wgroeneveld** [comment]
Might be a good idea to put in the documentation for the pipes that yarn2 users use `nodeLinker: node-modules` in their `.yarnrc.yml` config for now...

**Comment by arcanis** [comment]
> `Error: Cannot find module '@babel/preset-env'`

I don't know anything about Hugo, but this likely means that the PnP runtime isn't loaded when booting Babel. In general we would advise to 1/ add babel to the project's dependencies (locally, not globally, since they wouldn't be locked) 2/ tell Hugo to spawn it by using `yarn run -B babel` (instead of just `babel`).
