### ISSUE TITLE
Ordering matters for strikethrough and italics within titles

### ISSUE THREAD

**Issue by JohnathonNow** [gohugoio/hugo#8308]
A file with the following content anywhere in it fails to build:
<pre>
 ## *~~Test~~*
</pre>
However, the following content does work:
<pre>
 ## ~~*Test*~~
</pre>

The full error is below:
```
Start building sites … 
goroutine 56 [running]:
runtime/debug.Stack(0x23204a0, 0x2e89c60, 0xc0007bcb80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert.func1(0xc0009da900, 0xc000108180, 0xf, 0x59, 0x1, 0xc0009de090, 0xc0009e5918)
	/root/project/hugo/markup/goldmark/convert.go:238 +0x213
panic(0x1b2b000, 0xc0000401b0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/yuin/goldmark/renderer.(*renderer).Render.func2(0x232fd68, 0xc000236230, 0x1, 0x0, 0x2319258, 0xc000c7cdc0)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/renderer/renderer.go:164 +0x125
github.com/yuin/goldmark/ast.walkHelper(0x232fd68, 0xc000236230, 0xc0009e5378, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:492 +0x43
github.com/yuin/goldmark/ast.walkHelper(0x232e5c8, 0xc0005a0400, 0xc0009e5378, 0xc0008f6000, 0x0, 0x232e900)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:498 +0x16b
github.com/yuin/goldmark/ast.Walk(...)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:487
github.com/yuin/goldmark/renderer.(*renderer).Render(0xc000949090, 0x22e9a20, 0xc000c7e150, 0xc000108180, 0xf, 0x59, 0x232e5c8, 0xc0005a0400, 0xc0009e54e0, 0xc84538)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/renderer/renderer.go:161 +0x13c
github.com/gohugoio/hugo/markup/goldmark.(*tocTransformer).Transform.func1(0x232e5c8, 0xc0005a0400, 0x2323201, 0xc0000a5db0, 0xc000236150, 0xc000c7e150)
	/root/project/hugo/markup/goldmark/toc.go:89 +0x2c8
github.com/yuin/goldmark/ast.walkHelper(0x232e5c8, 0xc0005a0400, 0xc0009e5628, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:492 +0x43
github.com/yuin/goldmark/ast.walkHelper(0x232e928, 0xc000720f30, 0xc0009e5628, 0x3, 0x0, 0x0)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:498 +0x16b
github.com/yuin/goldmark/ast.walkHelper(0x232e4a8, 0xc000720ea0, 0xc0009e5628, 0x2dc4828, 0xc000108180, 0xc399e5)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:498 +0x16b
github.com/yuin/goldmark/ast.Walk(...)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/ast/ast.go:487
github.com/gohugoio/hugo/markup/goldmark.(*tocTransformer).Transform(0xc0000a5db0, 0xc000720ea0, 0x2323270, 0xc000236150, 0x2324798, 0xc000315b60)
	/root/project/hugo/markup/goldmark/toc.go:52 +0x1c5
github.com/yuin/goldmark/parser.(*parser).Parse(0xc0001e0a00, 0x2323270, 0xc000236150, 0xc0000c4138, 0x1, 0x1, 0xc000315b60, 0x59)
	/go/pkg/mod/github.com/yuin/goldmark@v1.3.2/parser/parser.go:867 +0x2e3
github.com/gohugoio/hugo/markup/goldmark.(*goldmarkConverter).Convert(0xc0009da900, 0xc000108180, 0xf, 0x59, 0x1, 0xc0009de090, 0x22ec2c0, 0xc0000c4128, 0x0, 0x0)
	/root/project/hugo/markup/goldmark/convert.go:248 +0x2c9
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContentWithConverter(0xc000ac2700, 0x22fd580, 0xc0009da900, 0xc000108180, 0xf, 0x59, 0x1246f01, 0xc000ac27cc, 0xc0009e5a38, 0x12744c0, ...)
	/root/project/hugo/hugolib/page__per_output.go:378 +0xeb
github.com/gohugoio/hugo/hugolib.(*pageContentOutput).renderContent(0xc000ac2700, 0xc000108180, 0xf, 0x59, 0xc000ae9501, 0x0, 0x22fd698, 0xc000b9c680, 0x42)
	/root/project/hugo/hugolib/page__per_output.go:374 +0x71
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func1(0x0, 0x0)
	/root/project/hugo/hugolib/page__per_output.go:126 +0xb05
github.com/gohugoio/hugo/hugolib.newPageContentOutput.func2(0x230e660, 0xc0009b5620, 0x1d2ceb8, 0x1, 0x1, 0xc000a50fa8)
	/root/project/hugo/hugolib/page__per_output.go:205 +0x26
github.com/gohugoio/hugo/lazy.(*Init).withTimeout.func1(0xc000c3fd20, 0x230e660, 0xc0009b5620, 0xc0009b5680)
	/root/project/hugo/lazy/init.go:176 +0x47
created by github.com/gohugoio/hugo/lazy.(*Init).withTimeout
	/root/project/hugo/lazy/init.go:175 +0x110
Total in 42 ms
Error: Error building site: "/home/john/scratch/hugo/bob/content/posts/bob.md:1:1": [BUG] goldmark: runtime error: index out of range [30] with length 20: create an issue on GitHub attaching the file in: /tmp/hugo_bugs/goldmark_02da3ec1f50cd2559a3b178a7ef27d6d.txt
```
The contents of `/tmp/hugo_bugs/goldmark_02da3ec1f50cd2559a3b178a7ef27d6d.txt` is simply:
<pre>

 ## *~~Test~~*
</pre>

This behavior also happens for underlined titles, and for every different title level.

### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.81.0-59D15C97 linux/amd64 BuildDate=2021-02-19T17:07:12Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?
Yes.

**Comment by bep** [comment]
Thanks for the report. This looks like it could be an issue with Goldmark. Could you create an issue at https://github.com/yuin/goldmark/issues and link back to this issue so we could track it?

**Comment by JohnathonNow** [comment]
Actually I was unable to recreate it with Goldmark, even with the Goldmark extensions, rendering options, and parser options that hugo uses.

After poking around for a bit it seems that the Table of Contents extension seems to be causing the issue, as commenting out this line fixes this particular issue:
https://github.com/gohugoio/hugo/blob/b3504a0ee812fe59be5fcfd961e2b67007241aff/markup/goldmark/convert.go#L101

Looking through the stack trace reveals that the index out of range error is from the renderer trying to render an ast node that it doesn't have a function registered for. I'm not very familiar with the hugo codebase, but it seems to be caused by the table of contents renderer not having the same extensions enabled as the one in `convert.go`, as it is just using the default renderer:
https://github.com/gohugoio/hugo/blob/b3504a0ee812fe59be5fcfd961e2b67007241aff/markup/goldmark/toc.go#L122-L128
A hacky solution seems to be to pass the `tocTransformer` the `Markdown`'s renderer instead of `goldmark.DefaultRenderer()`.
