### ISSUE TITLE
site rebuild (via static file changes) caused panic (*commandeer newWatcher)

### ISSUE THREAD

**Issue by whilei** [gohugoio/hugo#8368]
### Issue

I was running Hugo with `hugo server -D` while making a lot of changes to static files (mostly creating new PNG files, sometimes in new nested directories).

### What version of Hugo are you using (`hugo version`)?

```
go version
go version go1.16.2 linux/amd64

uname -a
Linux ubp52 5.2.9-050209-generic #201908160940 SMP Fri Aug 16 09:42:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

hugo version
Hugo Static Site Generator v0.80.0 linux/amd64 BuildDate: 2020-12-31T20:00:21Z
```

### Results

```
hugo server -D

[...]

Change of Static files detected, rebuilding site.
2021-03-27 16:33:43.715 -0500
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x1b0f7b3]

goroutine 429 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc000498e00, 0xc002f61260, 0xc003e765b8, 0xc0014c1800, 0x28, 0x40, 0xc0038bbb60)
        /build/hugo/parts/hugo/build/commands/hugo.go:1073 +0xc53
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc002f61260, 0xc000498e00, 0xc003e765b8, 0xc0038bbb60)
        /build/hugo/parts/hugo/build/commands/hugo.go:855 +0x1ff
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /build/hugo/parts/hugo/build/commands/hugo.go:851 +0x2cc
```

### Does this issue reproduce with the latest release?

Have not attempted to reproduce (time of writing latest is 0.82, bug seen on 0.80).

**Comment by alecthomas** [comment]
I also experienced this with 0.82:

```
File no longer exists in static dir, removing /images/foo/movie.mp4
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5465f4a]

goroutine 218 [running]:
github.com/gohugoio/hugo/commands.(*staticSyncer).syncsStaticEvents.func1(0xc001860500, 0xc0022a51d0, 0xc000d69a98, 0xc0032e60c0)
	/root/project/hugo/commands/static_syncer.go:104 +0x72a
github.com/gohugoio/hugo/commands.(*commandeer).doWithPublishDirs(0xc000246a80, 0xc000d69b30, 0xc000d34018, 0xc000d69b58, 0x453b677)
	/root/project/hugo/commands/hugo.go:584 +0x182
github.com/gohugoio/hugo/commands.(*staticSyncer).syncsStaticEvents(0xc0018fa768, 0xc002e80078, 0x1, 0x1, 0x1, 0xc002e80078)
	/root/project/hugo/commands/static_syncer.go:129 +0x85
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc000246a80, 0xc001a6d4e0, 0xc0018fa768, 0xc001514048, 0x1, 0x1, 0xc0018a0210)
	/root/project/hugo/commands/hugo.go:1081 +0xf45
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1(0xc001a6d4e0, 0xc000246a80, 0xc0018fa768, 0xc0018a0210)
	/root/project/hugo/commands/hugo.go:855 +0x1e9
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
	/root/project/hugo/commands/hugo.go:851 +0x2ce
```

**Comment by d-Rickyy-b** [comment]
I got the same issue today.

```
Change of Static files detected, rebuilding site.
2022-05-08 19:33:30.242 +0200
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x1ae1f81]

goroutine 90 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).handleEvents(0xc000530400, 0xc000d0bcb0, 0xc0000075b8, {0xc0008c0150?, 0x2, 0x2}, 0x726f6c6f632d646e?)
        /root/project/hugo/commands/hugo.go:1101 +0x721
github.com/gohugoio/hugo/commands.(*commandeer).newWatcher.func1()
        /root/project/hugo/commands/hugo.go:882 +0x26c
created by github.com/gohugoio/hugo/commands.(*commandeer).newWatcher
        /root/project/hugo/commands/hugo.go:873 +0x38d
```

Version info:
`hugo v0.98.0-165d299cde259c8b801abadc6d3405a229e449f6+extended windows/amd64 BuildDate=2022-04-28T10:23:30Z VendorInfo=gohugoio`
