### ISSUE TITLE
Panic: interface conversion: interface {} is map[string]string, not maps.Params

### ISSUE THREAD

**Issue by regisphilibert** [gohugoio/hugo#8679]
### What version of Hugo are you using (`hugo version`)?
`hugo v0.84.0-2C4689F7B+extended darwin/amd64 BuildDate=2021-06-18T17:14:27Z VendorInfo=gohugoio`

### Does this issue reproduce with the latest release?
Yes

I don't expect this to happen in a lot of settings but this happens in one repo of mine with a lot of functionality (it's a repo to test/develop/maintain several modules). I guess the ideal solution would simply the warning mentioning the template file/module/map key which might be affected.

Here's the full trace: 

```
panic: interface conversion: interface {} is map[string]string, not maps.Params

goroutine 1 [running]:
github.com/gohugoio/hugo/config.(*defaultConfigProvider).Merge(0xc0000b7040, 0x0, 0x0, 0x59c0ba0, 0xc00071f380)
        /hugo/config/defaultConfigProvider.go:205 +0x8b1
github.com/gohugoio/hugo/hugolib.configLoader.collectModules.func1(0xc0004ff580, 0x5f09938, 0xc000657e60)
        /hugo/hugolib/config.go:397 +0x19b
github.com/gohugoio/hugo/modules.(*Client).Collect(0xc000984f00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000044580, ...)
        /hugo/modules/collect.go:79 +0x253
github.com/gohugoio/hugo/hugolib.configLoader.collectModules(0x5f05f40, 0xc0000b7040, 0x5f06a40, 0x6b132a0, 0x5f09938, 0xc000657e60, 0x0, 0x0, 0xc0000460c4, 0x2c, ...)
        /hugo/hugolib/config.go:423 +0x47c
github.com/gohugoio/hugo/hugolib.LoadConfig(0x5f06a40, 0x6b132a0, 0x5f09938, 0xc000657e60, 0x0, 0x0, 0xc0000460c4, 0x2c, 0xc0000460c4, 0x2c, ...)
        /hugo/hugolib/config.go:161 +0xaf0
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0000c70a0, 0xc0000c0001, 0x5ed3ec0, 0xc00038a500)
        /hugo/commands/commandeer.go:298 +0x385
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0xc000a13860, 0x5ed12a0, 0xc000194678, 0x0, 0x0, 0x0, 0x0, 0xc0004cd300, 0x10, ...)
        /hugo/commands/commandeer.go:182 +0x257
github.com/gohugoio/hugo/commands.initializeConfig(0xc000050001, 0xc000a13860, 0x5ed12a0, 0xc000194678, 0x0, 0x5b7ac04, 0x32, 0x6b15420)
        /hugo/commands/hugo.go:121 +0x76
github.com/gohugoio/hugo/commands.(*modCmd).initConfig(0xc000194678, 0x8020101, 0x0, 0xc0008ffcd0, 0xc0008ffc60)
        /hugo/commands/mod.go:287 +0x65
github.com/gohugoio/hugo/commands.(*modCmd).withModsClient(0xc000194678, 0x1, 0xc000bbfcd8, 0xf, 0xc000053500)
        /hugo/commands/mod.go:269 +0x38
github.com/gohugoio/hugo/commands.(*modCmd).newCleanCmd.func1(0xc0004b7180, 0x6b137f0, 0x0, 0x0, 0x0, 0x0)
        /hugo/commands/mod.go:81 +0x207
github.com/spf13/cobra.(*Command).execute(0xc0004b7180, 0x6b137f0, 0x0, 0x0, 0xc0004b7180, 0x6b137f0)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000984780, 0xc00038a030, 0x5, 0x6)
        /go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/gohugoio/hugo/commands.Execute(0xc0001840a0, 0x2, 0x2, 0x4007da5, 0xc0000b8058, 0x54c5c10, 0x0)
        /hugo/commands/hugo.go:88 +0xb9
main.main()
        /hugo/main.go:23 +0x76
```

**Comment by SirUli** [comment]
I'm facing the exact same issue unfortunately. It works with the v0.83.x versions but fails with 0.84.0.

**Comment by SirUli** [comment]
@bep i still see the issue during ``hugo mod get -u`` with 0.84.1 extended.

```
panic: interface conversion: interface {} is string, not maps.Params
goroutine 1 [running]:
github.com/gohugoio/hugo/config.(*defaultConfigProvider).getNestedKeyAndMap(0xc0004e6ff0, 0xc0004ff9c0, 0xc, 0x1, 0xc, 0x2f6ac80, 0x0)
	/root/project/hugo/config/defaultConfigProvider.go:419 +0x38a
github.com/gohugoio/hugo/config.(*defaultConfigProvider).Set(0xc0004e6ff0, 0xc0004ff9c0, 0xc, 0x1c2b540, 0xc0005303b0)
	/root/project/hugo/config/defaultConfigProvider.go:171 +0x139
github.com/gohugoio/hugo/hugolib.configLoader.applyOsEnvOverrides(0x235a270, 0xc0004e6ff0, 0x2359780, 0x2faed40, 0x235c818, 0xc0003fe6f0, 0x0, 0x0, 0xc000050094, 0x5, ...)
	/root/project/hugo/hugolib/config.go:345 +0x494
github.com/gohugoio/hugo/hugolib.LoadConfig(0x2359780, 0x2faed40, 0x235c818, 0xc0003fe6f0, 0x0, 0x0, 0xc000050094, 0x5, 0xc000050094, 0x5, ...)
	/root/project/hugo/hugolib/config.go:114 +0x674
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0004f9180, 0xc0004f0000, 0x2327200, 0xc000010018)
	/root/project/hugo/commands/commandeer.go:298 +0x385
github.com/gohugoio/hugo/commands.newCommandeer(0x7fc2dd140000, 0xc000426680, 0x23245a0, 0xc000546210, 0x0, 0x0, 0x0, 0x0, 0x98, 0x8900000001e93ec0, ...)
	/root/project/hugo/commands/commandeer.go:182 +0x257
github.com/gohugoio/hugo/commands.initializeConfig(0x1f10000, 0xc000426680, 0x23245a0, 0xc000546210, 0x0, 0x6441b6, 0x1f22bde, 0x5)
	/root/project/hugo/commands/hugo.go:121 +0x76
github.com/gohugoio/hugo/commands.(*modCmd).initConfig(0xc000546210, 0x0, 0x1f1e981, 0x4, 0xc0003703c0)
	/root/project/hugo/commands/mod.go:287 +0x65
github.com/gohugoio/hugo/commands.(*modCmd).withModsClient(0xc000546210, 0xc0004dfc00, 0xc0004dfc98, 0xc0004ea900, 0xc0004dfce8)
	/root/project/hugo/commands/mod.go:269 +0x38
github.com/gohugoio/hugo/commands.(*commandsBuilder).newModCmd.func1(0xc00021d680, 0xc0003fade0, 0x1, 0x1, 0x0, 0x0)
	/root/project/hugo/commands/mod.go:199 +0x245
github.com/spf13/cobra.(*Command).execute(0xc00021d680, 0xc0003fade0, 0x1, 0x1, 0xc00021d680, 0xc0003fade0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc0003c1400, 0xc0003fabf0, 0x5, 0x6)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/gohugoio/hugo/commands.Execute(0xc00003c090, 0x3, 0x3, 0x4ce1c5, 0xc0000481d8, 0x198c920, 0x0)
	/root/project/hugo/commands/hugo.go:88 +0xb9
main.main()
	/root/project/hugo/main.go:23 +0x76
script returned exit code 2
```

Anything i can provide to solve that?

Best Regards, Uli
