### ISSUE TITLE
Panic and unexpected content with hugo new foo.unknownExtension

### ISSUE THREAD

**Issue by jmooring** [gohugoio/hugo#9072]
Tested with https://github.com/gohugoio/hugo/commit/471ed91c60cd36645794925cb4892cc820eae626. Not reproducible with v0.88.1.

I found this accidentally while creating pandoc content. I meant to type `hugo new foo.pdc` but instead typed `hugo new foo.pdoc`.

<details>
<summary>panic: [BUG] no Page found for ...</summary>

```text
panic: [BUG] no Page found for "/home/jmooring/code/hugo-testing/content/foo.pdoc"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc000268780, {0xc0007cf840, 0x31}, {0x0, 0x0})
        /home/jmooring/code/hugo/create/content.go:249 +0x354
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc000268780)
        /home/jmooring/code/hugo/create/content.go:218 +0x1ad
github.com/gohugoio/hugo/create.NewContent(0xc0000e4fd0, {0x0, 0x0}, {0x7ffe6b78c03c, 0x684985})
        /home/jmooring/code/hugo/create/content.go:94 +0x6ab
github.com/gohugoio/hugo/commands.(*newCmd).newContent(0xc00015d1d0, 0xc000414a00, {0xc00079fcc0, 0x1, 0x0})
        /home/jmooring/code/hugo/commands/new.go:83 +0x150
github.com/spf13/cobra.(*Command).execute(0xc000414a00, {0xc00079fc90, 0x1, 0x1})
        /home/jmooring/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00086a780)
        /home/jmooring/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/gohugoio/hugo/commands.Execute({0xc00003c0a0, 0x2, 0x2})
        /home/jmooring/code/hugo/commands/hugo.go:92 +0xb4
main.main()
        /home/jmooring/code/hugo/main.go:23 +0x58
```
</details>

The file (content/foo.pdoc) was created, but the content was unexpected.

With v0.881. the content is:

```text
---
title: "Foo"
date: 2021-10-22T10:38:20-07:00
draft: true
---
```

With https://github.com/gohugoio/hugo/commit/471ed91c60cd36645794925cb4892cc820eae626 the content is:

```text
---
title: "Content Placeholder"
_build:
  render: never
  list: never
  publishResources: false
---
```

I do not have an archetype for this file extension.

```text
archetypes/
└── default.md
```

**Comment by GGTruss** [comment]
I'm having this issue on 0.91 extended....

**Comment by jmooring** [comment]
@GGTruss This issue is closed. Please use the forum (https://discourse.gohugo.io) for questions and troubleshooting.
