### ISSUE TITLE
Postcss error with snap install of hugo v0.88.1+extended

### ISSUE THREAD

**Issue by PetersOtto** [gohugoio/hugo#9092]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ /snap/hugo/current/bin/hugo version

hugo v0.88.1+extended linux/amd64 BuildDate=2021-09-04T13:52:13Z
</pre>

### Operating System
<pre>
$ lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
</pre>

### Bug report
<pre>
Start building sites … 
hugo v0.88.1+extended linux/amd64 BuildDate=2021-09-04T13:52:13Z
ERROR 2021/10/28 13:03:47 POSTCSS: failed to transform "scss/bootstrap5.css" (text/css): /home/eddlinux/Dokumente/001_hugo/amgross_v1/amv1/node_modules/postcss-cli/index.js:3
import fs from 'fs-extra'
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Error: Error building site: POSTCSS: failed to transform "scss/preload.css" (text/css): /home/eddlinux/Dokumente/001_hugo/amgross_v1/amv1/node_modules/postcss-cli/index.js:3
import fs from 'fs-extra'
       ^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Built in 1752 ms

</pre>
 
@anthonyfok mentioned here ( https://github.com/gohugoio/hugo/issues/7278 ) , that the issue perhaps is not fixed. In my case it looks that it is the same bug, or? I am just a beginner with hugo, so it is possible that I did a configuration mistake. However I found no solution.

Do you have any idea?

**Comment by PetersOtto** [comment]
Dear jmooring
I uninstalled the snap version and installed the pre-built binary, like your suggestion.
It works perfect! Thank you!
