### ISSUE TITLE
Crash due to invalid paginator state n 00.89.4

### ISSUE THREAD

**Issue by nibbleshift** [gohugoio/hugo#9217]
### What version of Hugo are you using (`hugo version`)?

0.89.4 Extended

### Does this issue reproduce with the latest release?
Yes

Steps to reproduce.

1. Run "hugo server --disableFastRender"
2. Copy one or more markdown files into the content folder
3. Hugo detects changes and attempts to rebuild the site.
4. Hugo panics

```
Running in Fast Render Mode. For full rebuilds on change: hugo server --disableFastRender
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
Press Ctrl+C to stop
Change detected, rebuilding site.
2021-11-29 07:53:00.250 -0500
panic: invalid paginator state for "categories/aerospace"

goroutine 5097 [running]:
github.com/gohugoio/hugo/hugolib.(*Site).renderPaginator(0xc026696500, 0xc011e32420, {0x2557ed8, 0xc01cb96000})
        /home/steven/src/hugo/hugolib/site_render.go:192 +0x65f
github.com/gohugoio/hugo/hugolib.pageRenderer(0x6f6c2f2f3a707474, 0xc026696500, 0x7461632f33313331, 0x22736569726f6765, 0x206573776f72423e)
        /home/steven/src/hugo/hugolib/site_render.go:142 +0x2f2
created by github.com/gohugoio/hugo/hugolib.(*Site).renderPages
        /home/steven/src/hugo/hugolib/site_render.go:73 +0x112
```

**Comment by jmooring** [comment]
@nibbleshift I am unable to reproduce this with v0.89.4 running `hugo server --disableFastRender`. The test site has 100 posts, each with 'categories', and the categories list page is paginated (10 items per pager). Can you provide a minimal reproducible example?
