### ISSUE TITLE
regression: Panic when referencing an undefined output format

### ISSUE THREAD

**Issue by deining** [gohugoio/hugo#9530]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.92.2-CDF6A0D6+extended windows/amd64 BuildDate=2022-02-11T14:17:39Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes.

**How to reproduce:**

- Create a new hugo site and enter newly created directory:

```
hugo new site issue_9530
cd issue_9530
```

- Append a reference to a non existing output format at the end of `config.toml`, :

```
cat >> config.toml <<EOL
[outputs]
section = 'not_defined_yet'
EOL
```

- Invoke `hugo` and it will panic:

```
hugo
Total in 1 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x40 pc=0x1711148]

goroutine 1 [running]:
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
        /root/project/hugo/commands/commandeer.go:426 +0x588
sync.(*Once).doSlow(0x23e8190, 0x1eb181b)
        /usr/local/go/src/sync/once.go:68 +0xd2
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0004201e0)
        /root/project/hugo/commands/commandeer.go:377 +0x8a5
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x0, 0xc0000da0e0, {0x2396080, 0xc0003d6940}, 0xc0003d6af0, {0x0, 0x0, 0x0})
        /root/project/hugo/commands/commandeer.go:195 +0x310
github.com/gohugoio/hugo/commands.initializeConfig(0x2, 0x0, 0x0, 0xc0006ffd18, {0x2396080, 0xc0003d6940}, 0xc0004d74a0)
        /root/project/hugo/commands/hugo.go:125 +0x31
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc0004d2f00, {0x1e5ea46, 0x0, 0x0})
        /root/project/hugo/commands/commands.go:166 +0x155
github.com/spf13/cobra.(*Command).execute(0xc0004d2f00, {0xc00006e1e0, 0x0, 0x0})
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004d2f00)
        /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/gohugoio/hugo/commands.Execute({0xc00006e1e0, 0x0, 0x0})
        /root/project/hugo/commands/hugo.go:92 +0xb4
main.main()
        /root/project/hugo/main.go:23 +0x58
```

Note this is somehow related to a [discussion](https://discourse.gohugo.io/t/hugo-mod-init-fails-to-create-go-mod-if-hugo-detects-an-error-prematurely-in-site-config-toml/36687) on hugo's dicscourse forum started a month ago.

**Comment by jmooring** [comment]
With f7bc4cc5 and earlier:

> Error: from config: failed to resolve output format "not_defined_yet" from site config

With a2a660e and later:

> panic: runtime error: invalid memory address or nil pointer dereference

Similar to https://github.com/gohugoio/hugo/issues/9518
