### ISSUE TITLE
Hugo doesn't work with Asciidoctor and RVM

### ISSUE THREAD

**Issue by madhead** [gohugoio/hugo#9741]
### What version of Hugo are you using (`hugo version`)?

```
$ hugo version
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio
```

### Does this issue reproduce with the latest release?

Yes (0.96 is the latest release already)

### The issue

Hugo doesn't render any Asciidoc files when Asciidoctor is installed in RVM. There is a question on SO already: https://stackoverflow.com/q/71186825/750510. Answer suggests to use a system Ruby, and it indeed works. Also everything works in GitHub Workflows (no RVM there also).

Given a `Gemfile`:

```Gemfile
# frozen_string_literal: true
source 'https://rubygems.org'

gem 'asciidoctor'
``` 

And an RVM installation:

```shell
$ rvm ls
 * ruby-2.6.2 [ x86_64 ]
   ruby-2.7.2 [ x86_64 ]
=> ruby-3.1.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
```

I've installed the gems with `bundle install`.

The Gemlock:

```Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    asciidoctor (2.0.17)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  asciidoctor

BUNDLED WITH
   2.3.10
```

Asciidoctor is working:

```shell
$ asciidoctor --version
Asciidoctor 2.0.17 [https://asciidoctor.org]
Runtime Environment (ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ whereis asciidoctor
asciidoctor: /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/asciidoctor
```

But Hugo (`hugo serve`) doesn't render Asciidocs with an error like:

```
…
ERROR 2022/04/03 03:23:25 wiki/writing/_index.adoc: /home/madhead/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
ERROR 2022/04/03 03:23:25 wiki/writing/_index.adoc: from /home/madhead/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'
ERROR 2022/04/03 03:23:25 wiki/writing/_index.adoc: from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/asciidoctor:25:in `<main>'
ERROR 2022/04/03 03:23:25 wiki/writing/_index.adoc: from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/ruby_executable_hooks:22:in `eval'
ERROR 2022/04/03 03:23:25 wiki/writing/_index.adoc: from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/ruby_executable_hooks:22:in `<main>'
ERROR 2022/04/03 03:23:25 asciidoctor rendering wiki/writing/_index.adoc: failed to execute binary "asciidoctor" with args [--no-header-footer -]: /home/madhead/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem asciidoctor (>= 0.a) with executable asciidoctor (Gem::GemNotFoundException)
        from /home/madhead/.rvm/rubies/ruby-3.1.1/lib/ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'
        from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/asciidoctor:25:in `<main>'
        from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/ruby_executable_hooks:22:in `eval'
        from /home/madhead/.rvm/gems/ruby-3.1.1@madhead.me/bin/ruby_executable_hooks:22:in `<main>'
Error: Error building site: logged 120 error(s)
Built in 3383 ms
```

**Comment by madhead** [comment]
Installing the gem globally:

```shell
$ rvm use system

$ yay -S asciidoctor
resolving dependencies...
looking for conflicting packages...
warning: dependency cycle detected:
warning: rubygems will be installed before its ruby dependency
warning: dependency cycle detected:
warning: ruby-irb will be installed before its ruby dependency
warning: dependency cycle detected:
warning: ruby-reline will be installed before its ruby dependency

Packages (5) ruby-3.0.3-1  ruby-irb-1.4.1-1  ruby-reline-0.3.1-1  rubygems-3.3.5-1  asciidoctor-2.0.17-1

…

Also works:

```shell
$ hugo serve
Start building sites … 
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended linux/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio

                   | EN  
-------------------+-----
  Pages            | 45  
  Paginator pages  |  0  
  Non-page files   |  0  
  Static files     | 79  
  Processed images |  0  
  Aliases          |  2  
  Sitemaps         |  1  
  Cleaned          |  0  

Built in 2977 ms
```

**Comment by jmooring** [comment]
@madhead 

Please test with [v0.90.1](https://github.com/gohugoio/hugo/releases/tag/v0.90.1).

If that works, please test with [v0.91.0](https://github.com/gohugoio/hugo/releases/tag/v0.91.0).

**Comment by madhead** [comment]
@jmooring, 

`0.90.1` worked (https://github.com/gohugoio/hugo/releases/download/v0.90.1/hugo_extended_0.90.1_Linux-64bit.tar.gz)
`0.91.0` didn't

**Comment by madhead** [comment]
I have the security config clause, of course:

```yaml
security:
  exec:
    allow:
      - asciidoctor
```

**Comment by jmooring** [comment]
The default for `security.exec.osEnv` is:

```
[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']
```

Please change that to:

```
[security.exec]
osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|HOME)$']
```

and test again.

If that doesn't work, let's open it up (we'll know if we're on the right track):

```
[security.exec]
osEnv = ['.*']
```

**Comment by bep** [comment]
>Is this an expected behavior, and this ticked would be just closed?

Considering the matrix of possible combination, the default setup in Hugo (nor the documentation) could be expected to cover all possible combinations. This is unfortunate, but the `osEnv` filter was added there for a good (security) reason.
