### ISSUE TITLE
With multilingualism enabled, the "hugo new" command cannot create directories with the same name

### ISSUE THREAD

**Issue by Ice-Hazymoon** [gohugoio/hugo#9769]
hugo v0.96.0-2fd4a7d3d6845e75f8b8ae3a2a7bd91438967bbb+extended windows/amd64 BuildDate=2022-03-26T09:15:58Z VendorInfo=gohugoio

structure

```
content/
├── zh-hans
│   ├── posts
│   │   └── 2022
│   │       └── test
│   │           └── index.md
└── en-us
    └── posts
```

content/zh-hans/posts/2022/test/index.md

```
---
title: "test"
date: 2022-04-11T14:52:56+02:00
draft: false
type: "post"
---

hello world
```

/themes/mytheme/archetypes/default.md

```
---
title: "{{ replace .Name "-" " " | title }}"
date: {{ .Date }}
draft: true
type: "post"
---
```

config.yaml

```
theme: "mytheme"
languageCode: en-us
languages:
    zh-cn:
        contentDir: content/zh-hans
    en-us:
        contentDir: content/en-us
defaultContentLanguage: en-us
···
```

When I execute `hugo new posts/2022/test2/index.md`  the following error occurs:

```
panic: [BUG] no Page found for "C:\\Users\\Hazymoon\\Desktop\\Project\\Blog\\content\\en-us\\posts\\2022\\test2\\index.md"

goroutine 1 [running]:
github.com/gohugoio/hugo/create.(*contentBuilder).applyArcheType(0xc0009763c0, {0xc0007a9770, 0x50}, {0xc000a8ffa0, 0xa})
        /root/project/hugo/create/content.go:276 +0x35c
github.com/gohugoio/hugo/create.(*contentBuilder).buildFile(0xc0009763c0)
        /root/project/hugo/create/content.go:244 +0x1ad
github.com/gohugoio/hugo/create.NewContent.func1()
        /root/project/hugo/create/content.go:104 +0x2ad
github.com/gohugoio/hugo/create.NewContent(0xc0002f8840, {0x0, 0x0}, {0xc0000381a0, 0x19})
        /root/project/hugo/create/content.go:108 +0x609
github.com/gohugoio/hugo/commands.(*newCmd).newContent(0xc000616750, 0xc0004f1b80, {0xc000972bf0, 0x1, 0x0?})
        /root/project/hugo/commands/new.go:83 +0x159
github.com/spf13/cobra.(*Command).execute(0xc0004f1b80, {0xc000972bc0, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000146a00)
        /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/gohugoio/hugo/commands.Execute({0xc00008a050, 0x2, 0x3})
        /root/project/hugo/commands/hugo.go:93 +0xb4
main.main()
        /root/project/hugo/main.go:23 +0x57
```

`hugo new posts/2023/test2/index.md` will work fine

```
Content "C:\\Users\\Hazymoon\\Desktop\\Project\\Blog\\content\\en-us\\posts\\2023\\test2\\index.md" created
```

**Comment by jmooring** [comment]
These issue are possibly related:
- https://github.com/gohugoio/hugo/issues/9537
- https://github.com/gohugoio/hugo/issues/9204
- https://github.com/gohugoio/hugo/issues/9196
