### ISSUE TITLE
Panic when markup.defaultMarkdownHandler is invalid

### ISSUE THREAD

**Issue by NuLL3rr0r** [gohugoio/hugo#9968]
### What version of Hugo are you using (`hugo version`)?

<pre>
$ hugo version
hugo v0.100.1-0afb4866e345d31cbbcbab4349e43f1d36122806 linux/amd64 BuildDate=2022-06-01T10:11:48Z VendorInfo=gohugoio
</pre>

### Does this issue reproduce with the latest release?

Yes!

Version v0.99.1 is able to generate [my website](https://www.babaei.net/) (in the footer area you can see the version that is generated with). But both v0.100.0 and v0.100.1 throw the nil pointer dereference error:

```
hugo: no process found
Total in 1 ms
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x11732d1]

goroutine 1 [running]:
github.com/gohugoio/hugo/helpers.NewContentSpec({0x26084c0, 0xc0009f2700}, {0x2609798, 0xc0009ef680}, {0x26074a0, 0xc000652bc0}, 0xc00066f900)
	/root/project/hugo/helpers/content.go:87 +0x291
github.com/gohugoio/hugo/deps.New({{0x2609798, 0xc0009ef680}, 0xc000950bd0, 0xc0009f2700, {0x0, 0x0}, {0x26083b0, 0xc0004bb540}, {0xc000363000, 0x22, ...}, ...})
	/root/project/hugo/deps/deps.go:260 +0x4b7
github.com/gohugoio/hugo/hugolib.configLoader.applyDeps({{0x0, 0x0}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...}}, ...)
	/root/project/hugo/hugolib/hugo_sites.go:519 +0x31e
github.com/gohugoio/hugo/hugolib.newHugoSites({{0x2609798, 0xc0009ef680}, 0xc000950bd0, 0x0, {0x0, 0x0}, {0x26083b0, 0xc0004bb540}, {0x0, 0x0, ...}, ...}, ...)
	/root/project/hugo/hugolib/hugo_sites.go:406 +0x766
github.com/gohugoio/hugo/hugolib.NewHugoSites({{0x2609798, 0xc0009ef680}, 0xc000950bd0, 0x0, {0x0, 0x0}, {0x26083b0, 0xc0004bb540}, {0x0, 0x0, ...}, ...})
	/root/project/hugo/hugolib/hugo_sites.go:555 +0x158
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig.func3()
	/root/project/hugo/commands/commandeer.go:496 +0x838
sync.(*Once).doSlow(0x26083b0?, 0x20b6b25?)
	/usr/local/go/src/sync/once.go:68 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:59
github.com/gohugoio/hugo/commands.(*commandeer).loadConfig(0xc0003fc2d0)
	/root/project/hugo/commands/commandeer.go:422 +0xa19
github.com/gohugoio/hugo/commands.newCommandeer(0x1, 0x1, 0x0, 0xc0003fc1e0, {0x25f17c0?, 0xc0003b5370}, 0xc0003b5510, {0x0, 0x0, 0x0})
	/root/project/hugo/commands/commandeer.go:226 +0x310
github.com/gohugoio/hugo/commands.initializeConfig(0x0?, 0x3d?, 0x9e?, 0xc0009e3ca0?, {0x25f17c0?, 0xc0003b5370?}, 0x2f?)
	/root/project/hugo/commands/hugo.go:125 +0x31
github.com/gohugoio/hugo/commands.(*commandsBuilder).newHugoCmd.func1(0xc000962000, {0x203dd49?, 0x0?, 0x0?})
	/root/project/hugo/commands/commands.go:165 +0x135
github.com/spf13/cobra.(*Command).execute(0xc000962000, {0xc00003a200, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000962000)
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/gohugoio/hugo/commands.Execute({0xc00003a200, 0x0, 0x0})
	/root/project/hugo/commands/hugo.go:92 +0xb4
main.main()
	/root/project/hugo/main.go:23 +0x57
```

[Here is the version to reproduce it with](https://github.com/NuLL3rr0r/babaei-net-blog-source/tree/30202019d4fb8b1c65cb953c00c3612da5ff78a6).

**Comment by jmooring** [comment]
Your site config:

```
[markup]
defaultMarkdownHandler = "blackFriday"
```

From the release notes for [v0.100.0](https://github.com/gohugoio/hugo/releases/tag/v0.100.0)...

> We have removed Blackfriday as a Markdown option. It has been deprecated for a long time, its v1 version is not maintained anymore, and there are many known issues. Goldmark should be a mature replacement by now. 

Either remove that line from your site config, or set defaultMarkdownHandler to `goldmark`.

We should emit a descriptive error instead of panic.
